// Generated by tools/i18n-strings.py from tools/i18n_table.py: edit the table, not this file.
window.I18N_DICTS = window.I18N_DICTS || {};
window.I18N_DICTS.fr = {
 "title": "Contract signals — signaux dans les marchés publics",
 "exact": {
  "Language": "Langue",
  "Interface language": "Langue de l’interface",
  "Contract signals": "Contract signals",
  "Explore published procurement records from France, Chile, Colombia, Czechia, Paraguay, Portugal, Romania, Ukraine and the United Kingdom.": "Explorez les données publiées de commande publique de France, du Chili, de Colombie, de Tchéquie, du Paraguay, du Portugal, de Roumanie, d’Ukraine et du Royaume-Uni.",
  "Runs entirely in your browser: no account, cookies, analytics or uploads. Filters live in the link after": "Fonctionne entièrement dans votre navigateur : ni compte, ni cookies, ni mesure d’audience, ni envoi de données. Les filtres vivent dans le lien après",
  ", which browsers never send to a server; a chosen language is remembered in this browser only.": ", que les navigateurs n’envoient jamais à un serveur ; la langue choisie n’est mémorisée que dans ce navigateur.",
  "Explore contracts": "Explorer les contrats",
  "Dataset": "Jeu de données",
  "All countries": "Tous les pays",
  "France": "France",
  "Chile": "Chili",
  "Colombia": "Colombie",
  "Czechia": "Tchéquie",
  "Paraguay": "Paraguay",
  "Portugal": "Portugal",
  "Romania": "Roumanie",
  "Ukraine": "Ukraine",
  "United Kingdom": "Royaume-Uni",
  "France · Paris & Ardèche — contracts · DECP": "France · Paris et Ardèche — marchés · DECP",
  "France · six cities — contracts · DECP": "France · six villes — marchés · DECP",
  "France · Tours — procurement notices · BOAMP/TED": "France · Tours — avis de marchés · BOAMP/TED",
  "France · 3 Feb 2025 — consultation notices · BOAMP": "France · 3 févr. 2025 — avis de consultation · BOAMP",
  "France · nationwide sample — award lots + audit dossiers · BOAMP/CRC": "France · échantillon national — lots attribués + dossiers de contrôle · BOAMP/CRC",
  "All countries · every dataset side by side (not merged, not summed)": "Tous les pays · tous les jeux côte à côte (ni fusionnés, ni additionnés)",
  "Chile · MOP / Maule region / Puente Alto — licitaciones · Mercado Público": "Chili · MOP / région du Maule / Puente Alto — licitaciones · Mercado Público",
  "Colombia · MEN / Caldas / Usaquén — contracts · SECOP II": "Colombie · MEN / Caldas / Usaquén — contrats · SECOP II",
  "Czechia · Finance / Moravian-Silesian region / Ostrava — award notices · TED": "Tchéquie · Finances / région de Moravie-Silésie / Ostrava — avis d’attribution · TED",
  "Paraguay · Fernando de la Mora — contract records · DNCP OCDS": "Paraguay · Fernando de la Mora — fiches de contrats · DNCP OCDS",
  "Paraguay · MOPC / Central / Asunción — contract records · DNCP OCDS": "Paraguay · MOPC / Central / Asunción — fiches de contrats · DNCP OCDS",
  "Portugal · IP / Cávado / Lisboa — award notices · TED": "Portugal · IP / Cávado / Lisbonne — avis d’attribution · TED",
  "Romania · Finance / Cluj county / Cluj-Napoca — award notices · TED": "Roumanie · Finances / județ de Cluj / Cluj-Napoca — avis d’attribution · TED",
  "United Kingdom · FCDO / Lincolnshire / Milton Keynes — award notices · Find a Tender": "Royaume-Uni · FCDO / Lincolnshire / Milton Keynes — avis d’attribution · Find a Tender",
  "Ukraine · Health / Vinnytsia / Dnipro — contracts · Prozorro": "Ukraine · Santé / Vinnytsia / Dnipro — contrats · Prozorro",
  "Search": "Rechercher",
  "Buyer, supplier, subject, ID…": "Acheteur, fournisseur, objet, identifiant…",
  "Sort": "Trier",
  "Index · descending": "Indice · décroissant",
  "Index · ascending": "Indice · croissant",
  "Official findings first · outside the index": "Constats officiels d’abord · hors indice",
  "Amount · descending": "Montant · décroissant",
  "Amount · ascending": "Montant · croissant",
  "Signals · newest first": "Signaux · plus récents d’abord",
  "Date · newest first": "Date · plus récente d’abord",
  "Date · oldest first": "Date · plus ancienne d’abord",
  "Notice publication · newest first": "Publication de l’avis · plus récente d’abord",
  "Notice publication · oldest first": "Publication de l’avis · plus ancienne d’abord",
  "CPV sector · A–Z": "Secteur CPV · A–Z",
  "CPV sector · Z–A": "Secteur CPV · Z–A",
  "Buyer · A–Z": "Acheteur · A–Z",
  "Supplier · A–Z": "Fournisseur · A–Z",
  "Offers · ascending": "Offres · croissant",
  "Amount increase (%) · descending": "Hausse du montant (%) · décroissant",
  "Indicators · most signals first": "Indicateurs · plus de signaux d’abord",
  "Indicators · fewest signals first": "Indicateurs · moins de signaux d’abord",
  "Advanced filters": "Filtres avancés",
  "Advanced search and filters": "Recherche et filtres avancés",
  "Minimum amount": "Montant minimum",
  "CPV purchase sector": "Secteur d’achat CPV",
  "All sectors": "Tous les secteurs",
  "Group by": "Regrouper par",
  "No grouping": "Aucun regroupement",
  "Documented project": "Projet documenté",
  "CPV sector": "Secteur CPV",
  "Buyer": "Acheteur",
  "Supplier (SIREN)": "Fournisseur (SIREN)",
  "Project": "Projet",
  "All records": "Tous les enregistrements",
  "Documented projects only": "Projets documentés uniquement",
  "Assessment": "Évaluation",
  "Not assessed / excluded": "Non évalué / exclu",
  "Partial coverage": "Couverture partielle",
  "Zero after at least one evaluated check": "Zéro après au moins un contrôle évalué",
  "Minimum index": "Indice minimum",
  "All indices": "Tous les indices",
  "20 and more": "20 et plus",
  "40 and more": "40 et plus",
  "70 and more": "70 et plus",
  "Indicator": "Indicateur",
  "All indicators": "Tous les indicateurs",
  "Buyer with repeated low competition (France)": "Acheteur à faible concurrence répétée (France)",
  "Better-ranked bidder disqualified (Ukraine)": "Soumissionnaire mieux classé écarté (Ukraine)",
  "Short bidding period (if assessable)": "Délai de remise court (si évaluable)",
  "Term extended after award (Colombia)": "Durée prolongée après attribution (Colombie)",
  "Published long after the contract (transparency)": "Publié longtemps après le contrat (transparence)",
  "Official finding · outside the index": "Constat officiel · hors indice",
  "Notice content · no points": "Contenu de l’avis · sans points",
  "Procedure text / published reason": "Texte de procédure / motif publié",
  "Award criteria present": "Critères d’attribution présents",
  "Correction identified": "Rectificatif identifié",
  "Matched TED XML": "XML TED rapproché",
  "Legal context · no points": "Contexte juridique · sans points",
  "All contexts": "Tous les contextes",
  "Declared without competition · all amounts": "Déclaré sans mise en concurrence · tous montants",
  "Article R2122 cited": "Article R2122 cité",
  "R2122-1 cited · imperative urgency": "R2122-1 cité · urgence impérieuse",
  "R2122-3 cited · artistic, technical or exclusive-rights reasons": "R2122-3 cité · raisons artistiques, techniques ou de droits d’exclusivité",
  "Paraguay · amendments at the 20 % ceiling (Ley 7021 Art. 67)": "Paraguay · avenants au plafond de 20 % (Ley 7021 art. 67)",
  "Paraguay · complaint or investigation before the DNCP": "Paraguay · recours ou enquête devant la DNCP",
  "France · single-vendor software maintenance": "France · maintenance logicielle à fournisseur unique",
  "Colombia · public-to-public agreement": "Colombie · convention entre entités publiques",
  "Show only heuristic signals": "Afficher seulement les signaux heuristiques",
  "Show only official audit findings": "Afficher seulement les constats officiels de contrôle",
  "Show contract-linked final corruption judgments (if documented)": "Afficher les jugements définitifs de corruption liés au contrat (si documentés)",
  "Show investigations reported at the time (current status unknown)": "Afficher les enquêtes signalées à l’époque (statut actuel inconnu)",
  "Clear advanced filters": "Effacer les filtres avancés",
  "Your browser may block automatic loading of a local file. Open": "Votre navigateur peut bloquer le chargement automatique d’un fichier local. Ouvrez",
  "with the file picker below, or serve this folder with": "avec le sélecteur de fichier ci-dessous, ou servez ce dossier avec",
  "Open your own JSON file": "Ouvrir votre propre fichier JSON",
  "Read in this browser only, never uploaded.": "Lu uniquement dans ce navigateur, jamais envoyé.",
  "File format": "Format du fichier",
  "Signals prompt review, not accusations. A zero or missing label does not mean a contract is clean.": "Les signaux invitent à vérifier, ils n’accusent pas. Un zéro ou l’absence d’étiquette ne signifie pas qu’un contrat est irréprochable.",
  "How to read these results ↓": "Comment lire ces résultats ↓",
  "Loading data…": "Chargement des données…",
  "Export all filtered records:": "Exporter tous les enregistrements filtrés :",
  "← Previous": "← Précédent",
  "Next →": "Suivant →",
  "Rows/page": "Lignes/page",
  "Copy page summary": "Copier le résumé de la page",
  "Table pagination": "Pagination du tableau",
  "Copy a short summary of this page with source URLs. Check for personal data before pasting into an external service.": "Copie un court résumé de cette page avec les URL des sources. Vérifiez les données personnelles avant de le coller dans un service externe.",
  "Download every filtered record (all pages) as CSV. Built in your browser; nothing is uploaded.": "Télécharge tous les enregistrements filtrés (toutes les pages) en CSV. Produit dans votre navigateur ; rien n’est envoyé.",
  "Download every filtered record (all pages) as JSON, with the current view and caveats. Built in your browser; nothing is uploaded.": "Télécharge tous les enregistrements filtrés (toutes les pages) en JSON, avec la vue courante et les réserves. Produit dans votre navigateur ; rien n’est envoyé.",
  "Contracts and documented records — click a subject to open the details and history.": "Marchés et enregistrements documentés — cliquez sur un objet pour ouvrir le détail et l’historique.",
  "Contracts table, horizontal scrolling possible": "Tableau des marchés, défilement horizontal possible",
  "Date": "Date",
  "Supplier": "Fournisseur",
  "Subject": "Objet",
  "Declared amount": "Montant déclaré",
  "Offers": "Offres",
  "Indicators": "Indicateurs",
  "Index": "Indice",
  "Purchase sector, not the supplier’s NAF activity": "Secteur d’achat, pas l’activité NAF du fournisseur",
  "Declared financial stake, outside the index; not necessarily an expense": "Enjeu financier déclaré, hors indice ; pas nécessairement une dépense",
  "Vigilance index": "Indice de vigilance",
  "Vigilance scale, not a regularity measure": "Échelle de vigilance, pas une mesure de régularité",
  "How to read the results": "Comment lire les résultats",
  "Documented project dossier": "Dossier de projet documenté",
  "Buyer or supplier profile": "Profil d’acheteur ou de fournisseur",
  "Enable JavaScript to load and explore the data.": "Activez JavaScript pour charger et explorer les données.",
  "The indicators flag characteristics for review—not proof of irregularity, favoritism or corruption.": "Les indicateurs signalent des caractéristiques à examiner — pas une preuve d’irrégularité, de favoritisme ou de corruption.",
  "Public data can contain errors. A flag does not imply illegal behavior; no flag does not guarantee regularity. The copy button copies only summaries of the current page; large pages may exceed chat limits. Export CSV/JSON downloads every filtered record; an empty index cell means not assessed, not zero. Review personal data before pasting into any external service.": "Les données publiques peuvent contenir des erreurs. Un signal n’implique pas un comportement illégal ; son absence ne garantit pas la régularité. Le bouton de copie ne copie que les résumés de la page courante ; les pages longues peuvent dépasser les limites d’un chat. L’export CSV/JSON télécharge tous les enregistrements filtrés ; une cellule d’indice vide signifie « non évalué », pas zéro. Vérifiez les données personnelles avant de les coller dans un service externe.",
  "Data scope and limits": "Périmètre et limites des données",
  "Exploratory 24-month history: 2,594 DECP contracts from Paris and Ardèche, notified in 2024–2025. Modifications published may be later than 2025. This is not a guarantee of exhaustiveness of actual purchases.": "Historique exploratoire de 24 mois : 2 594 marchés DECP de Paris et de l’Ardèche, notifiés en 2024–2025. Les modifications publiées peuvent être postérieures à 2025. Ce n’est pas une garantie d’exhaustivité des achats réels.",
  "Datasets are not merged; they may describe the same purchases. Do not add their amounts. “—” means unknown, not safe.": "Les jeux de données ne sont pas fusionnés ; ils peuvent décrire les mêmes achats. N’additionnez pas leurs montants. « — » signifie inconnu, pas sans risque.",
  "Coverage and provenance (JSON)": "Couverture et provenance (JSON)",
  "Sources and how to verify": "Sources et comment vérifier",
  "Index and evidence labels": "Indice et étiquettes de preuve",
  "0 · no threshold crossed in evaluated checks": "0 · aucun seuil franchi dans les contrôles évalués",
  "1–19 · low": "1–19 · faible",
  "20–39 · moderate": "20–39 · modérée",
  "40–69 · high": "40–69 · élevée",
  "70–100 · very high": "70–100 · très élevée",
  "Not assessed ≠ zero": "Non évalué ≠ zéro",
  "Index v3.1 is an editorial sorting aid, not a probability; zero requires an evaluated check and certifies nothing. Unknowns are shown separately. Amounts and official findings never add points.": "L’indice v3.1 est une aide éditoriale au tri, pas une probabilité ; zéro exige un contrôle évalué et ne certifie rien. Les inconnues sont affichées à part. Les montants et les constats officiels n’ajoutent jamais de points.",
  "One French dossier has a dated news report of an investigative step; its current status is unknown. No comparable report is linked in the Colombian or Paraguayan pilots. No contract-specific final corruption judgment is documented in these datasets. French CRC audit observations are not convictions. No match means": "Un dossier français dispose d’un article de presse daté sur un acte d’enquête ; son statut actuel est inconnu. Aucun article comparable n’est lié dans les pilotes colombien ou paraguayen. Aucun jugement définitif de corruption propre à un contrat n’est documenté dans ces données. Les observations des CRC ne sont pas des condamnations. L’absence de correspondance signifie",
  "not established here, not cleared": "non établi ici, pas écarté",
  "Method: vigilance index": "Méthode : indice de vigilance",
  "Editorial choices, not calibrated to predict irregularity.": "Choix éditoriaux, non calibrés pour prédire l’irrégularité.",
  "Comparison v2.1/v3 and ranking sensitivity (JSON)": "Comparaison v2.1/v3 et sensibilité du classement (JSON)",
  ". Software verification is not legal or statistical validation. Flagged and unflagged cases must be reviewed.": ". La vérification logicielle n’est pas une validation juridique ou statistique. Les cas signalés et non signalés doivent être examinés.",
  "Full method and excerpt review": "Méthode complète et revue d’extraits",
  "Colombia pilot method": "Méthode du pilote colombien",
  "Countries proposed for upcoming pilots": "Pays proposés pour les prochains pilotes",
  "Source links must be kept. Every official finding must point to the document of the originating authority and to its relevant passage. Always consult the complete document and any responses from the organization concerned.": "Les liens vers les sources doivent être conservés. Tout constat officiel doit renvoyer au document de l’autorité d’origine et au passage pertinent. Consultez toujours le document complet et les réponses de l’organisme concerné.",
  "Version 3.1.": "Version 3.1.",
  "Coverage:": "Couverture :",
  "Weights:": "Pondérations :",
  "SECOP II · Colombia pilot:": "SECOP II · pilote colombien :",
  "full method": "méthode complète",
  "Tours full notices:": "Avis complets de Tours :",
  "Six additional municipalities:": "Six communes supplémentaires :",
  "Short bidding period:": "Délai de remise court :",
  "Concentrated awards:": "Attributions concentrées :",
  "Repeated direct awards:": "Attributions directes répétées :",
  "Groupings:": "Regroupements :",
  "Published long after the contract (transparency):": "Publié longtemps après le contrat (transparence) :",
  "Declared amount increase:": "Hausse du montant déclaré :",
  "Repeated low competition:": "Faible concurrence répétée :",
  "Score = competition maximum (up to 60) + execution/duration maximum (up to 40) + transparency maximum (up to 16), capped at 100, with no renormalization by coverage, dataset or filter. Every check belongs to one indicator catalogue shared by all countries (": "Score = maximum de concurrence (jusqu’à 60) + maximum d’exécution/durée (jusqu’à 40) + maximum de transparence (jusqu’à 16), plafonné à 100, sans renormalisation par couverture, jeu de données ou filtre. Chaque contrôle appartient à un catalogue d’indicateurs commun à tous les pays (",
  "); eligibility and thresholds follow each jurisdiction. Official findings are separate documentary elements, never points. No amount-based uplift. No target proportion of flagged contracts.": ") ; l’éligibilité et les seuils suivent chaque juridiction. Les constats officiels sont des éléments documentaires distincts, jamais des points. Aucune majoration selon le montant. Aucune proportion cible de marchés signalés.",
  "Not assessed": "Non évalué",
  "Partial data": "Données partielles",
  "No signal triggered": "Aucun signal déclenché",
  "Low vigilance": "Vigilance faible",
  "Moderate vigilance": "Vigilance modérée",
  "High vigilance": "Vigilance élevée",
  "Very high vigilance": "Vigilance très élevée",
  "Very high": "Très élevée",
  "High": "Élevée",
  "Moderate": "Modérée",
  "Low": "Faible",
  "Documented · public source": "Documenté · source publique",
  "To verify · research lead": "À vérifier · piste de recherche",
  "Contract-period start · not signature": "Début de la période du contrat · pas la signature",
  "BOAMP publication": "Publication BOAMP",
  "Ambiguous identifier / versions · calculations excluded": "Identifiant / versions ambigus · calculs exclus",
  "Conflicting modification versions": "Versions de modification contradictoires",
  "Official audit finding · not a conviction": "Constat officiel de contrôle · pas une condamnation",
  "Investigation reported at the time · current status unknown": "Enquête signalée à l’époque · statut actuel inconnu",
  "Final judgment linked to this contract": "Jugement définitif lié à ce marché",
  "unknown CPV": "CPV inconnu",
  "No result. Try lowering the minimum amount or changing the filters.": "Aucun résultat. Essayez de baisser le montant minimum ou de changer les filtres.",
  "every data/*.json file above": "tous les fichiers data/*.json ci-dessus",
  "Single offer in a competitive procedure": "Offre unique dans une procédure concurrentielle",
  "Award without competition": "Attribution sans mise en concurrence",
  "Repeated single-offer wins by the same supplier": "Attributions répétées à offre unique au même fournisseur",
  "Repeated awards without competition to the same supplier": "Attributions répétées sans concurrence au même fournisseur",
  "Buyer with repeated low competition": "Acheteur à faible concurrence répétée",
  "Concentrated awards": "Attributions concentrées",
  "Better-ranked bidder disqualified": "Soumissionnaire mieux classé écarté",
  "Short bidding period": "Délai de remise court",
  "Long declared duration": "Durée déclarée longue",
  "Amount increase after award": "Hausse du montant après attribution",
  "Term extended after award": "Durée prolongée après attribution",
  "Published long after the contract": "Publié longtemps après le contrat",
  "· competition": "· concurrence",
  "· execution/duration": "· exécution/durée",
  "· transparency": "· transparence",
  "· competition · not added": "· concurrence · non ajouté",
  "· execution/duration · not added": "· exécution/durée · non ajouté",
  "· transparency · not added": "· transparence · non ajouté",
  "single-vendor software maintenance": "maintenance logicielle à fournisseur unique",
  "public-to-public agreement": "convention entre entités publiques",
  "amendments at the 20 % ceiling": "avenants au plafond de 20 %",
  "Declared duration ≥ 10 years": "Durée déclarée ≥ 10 ans",
  "Relative increase in declared amount": "Hausse relative du montant déclaré",
  "Repeated low competition": "Faible concurrence répétée",
  "Repeated direct awards": "Attributions directes répétées",
  "Published more than 120 days after the contract": "Publié plus de 120 jours après le contrat",
  "Award declared without supplier plurality or under manifest urgency": "Attribution déclarée sans pluralité d’offreurs ou pour urgence manifeste",
  "Repeated awards declared without supplier plurality": "Attributions répétées déclarées sans pluralité d’offreurs",
  "Concentrated awards within a contract type": "Attributions concentrées dans un type de contrat",
  "Long declared duration (≥ 36 months)": "Durée déclarée longue (≥ 36 mois)",
  "Declared term more than doubled by extensions (> 100 %)": "Durée déclarée plus que doublée par des prolongations (> 100 %)",
  "Single tenderer in a competitive procedure": "Soumissionnaire unique dans une procédure concurrentielle",
  "Award by exception to competitive procedure (CVE)": "Attribution par exception à la procédure concurrentielle (CVE)",
  "Repeated single-tenderer awards to the same supplier": "Attributions répétées à soumissionnaire unique au même fournisseur",
  "Repeated exception awards to the same supplier": "Attributions répétées par exception au même fournisseur",
  "Concentrated awards within a procurement category": "Attributions concentrées dans une catégorie d’achat",
  "Declared amount increase > 20 %": "Hausse du montant déclaré > 20 %",
  "Award without competition (Negotiated procedure without competition)": "Attribution sans mise en concurrence (procédure négociée sans concurrence)",
  "Repeated single-offer awards to the same supplier": "Attributions répétées à offre unique au même fournisseur",
  "Concentrated awards within a category": "Attributions concentrées dans une catégorie",
  "Better-ranked bidder disqualified before the award": "Soumissionnaire mieux classé écarté avant l’attribution",
  "Award without competition (Negotiated without prior publication)": "Attribution sans mise en concurrence (négocié sans publication préalable)",
  "Award without competition (Award without prior publication)": "Attribution sans mise en concurrence (attribution sans publication préalable)",
  "Award without competition (Direct deal (trato directo))": "Attribution sans mise en concurrence (trato directo)",
  "Signal": "Signal",
  "Evaluated · threshold not crossed": "Évalué · seuil non franchi",
  "Not assessable": "Non évaluable",
  "Out of scope": "Hors champ",
  "(unknown applicability)": "(applicabilité inconnue)",
  "Open procedure": "Procédure ouverte",
  "Restricted procedure": "Procédure restreinte",
  "Verify it yourself": "Vérifiez par vous-même",
  "Buyer profile": "Profil de l’acheteur",
  "Supplier profile": "Profil du fournisseur",
  "Separate financial stake: the declared amount increases no weight. An increase uses only the comparable percentage, not a payments total. No points for an official finding, a project or an R2122 citation.": "Enjeu financier distinct : le montant déclaré n’augmente aucun poids. Une hausse n’utilise que le pourcentage comparable, pas un total de paiements. Aucun point pour un constat officiel, un projet ou une citation R2122.",
  "Not assessed: no applicable check could be evaluated. This is not a zero score.": "Non évalué : aucun contrôle applicable n’a pu être évalué. Ce n’est pas un score nul.",
  "No heuristic conclusion: not assessed. The documents and findings remain consultable.": "Aucune conclusion heuristique : non évalué. Les documents et constats restent consultables.",
  "No threshold crossed among the evaluated checks only. Unknowns do not prove an absence of risk.": "Aucun seuil franchi parmi les seuls contrôles évalués. Les inconnues ne prouvent pas une absence de risque.",
  "Declared legal basis — context, not an indicator": "Base juridique déclarée — contexte, pas un indicateur",
  "Single-vendor software maintenance — context, not an indicator": "Maintenance logicielle à fournisseur unique — contexte, pas un indicateur",
  "SECOP II — declared procedure and justification": "SECOP II — procédure et justification déclarées",
  "DNCP OCDS — published contract context": "DNCP OCDS — contexte publié du contrat",
  "Published contract history": "Historique publié du marché",
  "Process page on the official portal: ": "Page de la procédure sur le portail officiel : ",
  "Current public identity — not historical": "Identité publique actuelle — non historique",
  "Documented official finding — separate from the index": "Constat officiel documenté — distinct de l’indice",
  "Reported investigation — separate from findings and index": "Enquête signalée — distincte des constats et de l’indice",
  "Paraguayan checks and their editorial thresholds: docs/score-paraguay.md. A signal is not a finding of irregularity.": "Contrôles paraguayens et leurs seuils éditoriaux : docs/score-paraguay.md. Un signal n’est pas un constat d’irrégularité.",
  "Exact queries, retrieval times, counts and exclusions (coverage JSON)": "Requêtes exactes, dates de collecte, comptages et exclusions (JSON de couverture)",
  "To check one contract: open its row and follow “Verify it yourself”. Official pages come first; if a link has moved, search the portal for the identifiers listed there.": "Pour vérifier un marché : ouvrez sa ligne et suivez « Vérifiez par vous-même ». Les pages officielles viennent d’abord ; si un lien a changé, cherchez sur le portail les identifiants indiqués.",
  "This buyer": "Cet acheteur",
  "This supplier": "Ce fournisseur",
  "Whole dataset": "Jeu complet",
  "not evaluated": "non évalué",
  "Main suppliers": "Principaux fournisseurs",
  "Main buyers": "Principaux acheteurs",
  "A profile describes published declarations and heuristic signals only; a high rate is a reason to read the sources, not a finding.": "Un profil ne décrit que des déclarations publiées et des signaux heuristiques ; un taux élevé invite à lire les sources, ce n’est pas un constat.",
  "Close profile and show all contracts": "Fermer le profil et afficher tous les marchés",
  "This source publishes no publication date to compare with the contract date: out of scope.": "Cette source ne publie pas de date de publication à comparer à la date du contrat : hors champ.",
  "No offers/proposals table in this SECOP II extract: the number of offers was never imported; out of scope.": "Pas de table d’offres dans cet extrait SECOP II : le nombre d’offres n’a jamais été importé ; hors champ.",
  "No publication–deadline chronology in this extract: bidding period out of scope.": "Pas de chronologie publication–date limite dans cet extrait : délai de remise hors champ.",
  "Depends on offer counts, absent from this extract: repetition of low competition out of scope.": "Dépend du nombre d’offres, absent de cet extrait : répétition de faible concurrence hors champ.",
  "This contract is not among the awards declared without supplier plurality or under manifest urgency: outside the repetition scope.": "Ce contrat ne fait pas partie des attributions déclarées sans pluralité d’offreurs ou pour urgence manifeste : hors du champ de la répétition.",
  "Initial notice and timetable not imported.": "Avis initial et calendrier non importés.",
  "Conflicting versions: calculations excluded.": "Versions contradictoires : calculs exclus.",
  "Explicitly competitive procedure: no direct-award signal.": "Procédure explicitement concurrentielle : pas de signal d’attribution directe.",
  "This contract is explicitly competitive: direct repetition out of scope.": "Ce marché est explicitement concurrentiel : répétition directe hors champ.",
  "This contract is not a single-offer competitive award: outside the repeated-single-offer scope.": "Ce marché n’est pas une attribution concurrentielle à offre unique : hors du champ de l’offre unique répétée.",
  "No duration threshold validated for this jurisdiction: out of scope.": "Aucun seuil de durée validé pour cette juridiction : hors champ.",
  "Not a single-offer competitive award: outside the repetition scope.": "Pas une attribution concurrentielle à offre unique : hors du champ de la répétition.",
  "No validated minimum period for this jurisdiction in this method: out of scope.": "Aucun délai minimum validé pour cette juridiction dans cette méthode : hors champ.",
  "Single holder or insufficient/unknown cohort context; no name-based matching.": "Titulaire unique ou contexte de cohorte insuffisant/inconnu ; aucun rapprochement par le nom.",
  "Published contract history not available for this record; increase check not applicable.": "Historique publié du marché indisponible pour cet enregistrement ; contrôle de hausse non applicable.",
  "Not an award without competition: outside the repetition scope.": "Pas une attribution sans mise en concurrence : hors du champ de la répétition.",
  "No modification published in this extract; this does not prove the absence of an amendment.": "Aucune modification publiée dans cet extrait ; cela ne prouve pas l’absence d’avenant.",
  "No eligible competitive context: no zero rate assumed.": "Aucun contexte concurrentiel éligible : aucun taux nul supposé.",
  "An offer expected in a direct award adds nothing; competitive procedure not established if unknown.": "Une offre attendue dans une attribution directe n’ajoute rien ; procédure concurrentielle non établie si inconnue.",
  "Competitive character unknown.": "Caractère concurrentiel inconnu.",
  "Competitive character of this contract unknown: direct repetition not assessable.": "Caractère concurrentiel de ce marché inconnu : répétition directe non évaluable.",
  "Declared duration unknown.": "Durée déclarée inconnue.",
  "Positive number of offers unknown or unusable.": "Nombre positif d’offres inconnu ou inutilisable.",
  "Contract modification notices are separate TED notices, not imported: increase out of scope.": "Les avis de modification sont des avis TED distincts, non importés : hausse hors champ.",
  "Direct-contract report (reporting): ordinary, mostly low-value purchases recorded without a procedure; not scored, like the bare Colombian direct modality.": "Rapport de contrat direct (reporting) : achats ordinaires, surtout de faible valeur, enregistrés sans procédure ; non notés, comme la modalité directe colombienne.",
  "Contract change notices are separate Find a Tender notices, not imported: increase out of scope.": "Les avis de modification sont des avis Find a Tender distincts, non importés : hausse hors champ.",
  "This source lists licitaciones only: direct deals (trato directo) are published as purchase orders, not imported. Out of scope, not clear.": "Cette source ne liste que des licitaciones : les tratos directos sont publiés comme bons de commande, non importés. Hors champ, pas écarté.",
  "Contract modifications are not in this OCDS source: increase out of scope.": "Les modifications de contrat ne figurent pas dans cette source OCDS : hausse hors champ.",
  "Declared duration field missing: applicability not established.": "Champ de durée déclarée absent : applicabilité non établie.",
  "Holder identity unknown: applicability not established.": "Identité du titulaire inconnue : applicabilité non établie.",
  "Supplier identity or category unknown: applicability not established.": "Identité du fournisseur ou catégorie inconnue : applicabilité non établie.",
  "Unverified record: calculations excluded.": "Enregistrement non vérifié : calculs exclus.",
  "Duplicate contract identifier: calculations excluded.": "Identifiant de marché en double : calculs exclus.",
  "Not an individual awarded contract with a contract date.": "Pas un marché attribué individuel avec une date de contrat.",
  "Contract date or publication date missing: delay not assessable.": "Date du contrat ou de publication manquante : délai non évaluable.",
  "Find a Tender award notices can carry the date of an original contract signed years earlier (modification notices under PCR 2015 Regulation 72) or of admission to a dynamic purchasing system: the delay would not measure late publication. Out of scope.": "Les avis d’attribution Find a Tender peuvent porter la date d’un contrat initial signé des années plus tôt (avis de modification au titre de la regulation 72 des PCR 2015) ou d’admission à un système d’acquisition dynamique : le délai ne mesurerait pas une publication tardive. Hors champ.",
  "Agriculture and fisheries": "Agriculture et pêche",
  "Energy and fuels": "Énergie et carburants",
  "Mining and minerals": "Mines et minéraux",
  "Food and beverages": "Alimentation et boissons",
  "Agricultural machinery": "Machines agricoles",
  "Clothing and equipment": "Habillement et équipement",
  "Leather and textiles": "Cuir et textiles",
  "Printed matter and publishing": "Imprimés et édition",
  "Chemical products": "Produits chimiques",
  "Computer and office equipment": "Matériel informatique et de bureau",
  "Electrical equipment": "Équipements électriques",
  "Telecommunications — equipment": "Télécommunications — équipements",
  "Medical equipment and pharmacy": "Équipements médicaux et pharmacie",
  "Vehicles and transport — equipment": "Véhicules et transport — équipements",
  "Security and defence — equipment": "Sécurité et défense — équipements",
  "Music, sport and leisure — equipment": "Musique, sport et loisirs — équipements",
  "Measurement, laboratory and optics": "Mesure, laboratoire et optique",
  "Furniture and miscellaneous equipment": "Mobilier et équipements divers",
  "Collected and purified water": "Eau captée et épurée",
  "Industrial machinery": "Machines industrielles",
  "Construction and mining machinery": "Engins de chantier et d’extraction",
  "Construction materials": "Matériaux de construction",
  "Construction work": "Travaux de construction",
  "Software": "Logiciels",
  "Repair and maintenance": "Réparation et entretien",
  "Installation": "Installation",
  "Hotel and restaurant services": "Hôtellerie et restauration",
  "Transport": "Transport",
  "Transport — ancillary services": "Transport — services annexes",
  "Post and telecommunications": "Postes et télécommunications",
  "Utility distribution services": "Distribution de services publics",
  "Finance and insurance": "Finance et assurance",
  "Real estate": "Immobilier",
  "Architecture, engineering and inspection": "Architecture, ingénierie et contrôle",
  "IT services": "Services informatiques",
  "Research and development": "Recherche et développement",
  "Administration, defence and social security": "Administration, défense et sécurité sociale",
  "Oil and gas services": "Services pétroliers et gaziers",
  "Agricultural and forestry services": "Services agricoles et forestiers",
  "Consulting, communication and business services": "Conseil, communication et services aux entreprises",
  "Education and training": "Éducation et formation",
  "Health and social services": "Santé et action sociale",
  "Waste, sanitation and environment": "Déchets, assainissement et environnement",
  "Culture, leisure and sport": "Culture, loisirs et sport",
  "Other services": "Autres services",
  "Sector not specified": "Secteur non précisé",
  "essential data published on the buyer profile": "les données essentielles publiées sur le profil d’acheteur",
  "BOAMP award notice": "l’avis d’attribution au BOAMP",
  "TED award notice": "l’avis d’attribution TED",
  "Unreadable date: delay not assessable.": "Date illisible : délai non évaluable.",
  "Award explicitly declared without competition: 18 points, all amounts. May be legal; no bonus for an R2122 citation.": "Attribution explicitement déclarée sans mise en concurrence : 18 points, tous montants. Peut être légale ; pas de bonus pour une citation du R2122.",
  "Rule reserved for explicitly open non-accelerated procedures; this record’s known type is out of scope.": "Règle réservée aux procédures ouvertes explicites non accélérées ; le type connu de cet enregistrement est hors champ.",
  "No history for an identified holder: repetition unknown.": "Pas d’historique pour un titulaire identifié : répétition inconnue.",
  "A citation proves neither that the legal conditions are met nor an irregularity. A single offer received does not demonstrate exclusivity. No points added; no inference about other contracts.": "Une citation ne prouve ni que les conditions légales sont remplies, ni une irrégularité. Une seule offre reçue ne démontre pas l’exclusivité. Aucun point ajouté ; aucune inférence sur d’autres marchés.",
  "Article R2122 not found in the imported object or procedure. Justification unknown in this extract, not absence of justification.": "Article R2122 non trouvé dans l’objet ou la procédure importés. Justification inconnue dans cet extrait, pas absence de justification.",
  "SIREN matching derived from an explicitly typed French identifier. Name and status of the legal unit observed at retrieval time, not those of each establishment nor those at the contract date. No points for the name or status; no link between companies inferred.": "Rapprochement SIREN dérivé d’un identifiant français explicitement typé. Nom et état de l’unité légale observés à la date de consultation, pas ceux de chaque établissement ni ceux à la date du marché. Aucun point pour le nom ou l’état ; aucun lien entre entreprises inféré.",
  "Available published versions — absence of a published amendment ≠ absence of a real modification.": "Versions publiées disponibles — l’absence d’avenant publié ≠ l’absence de modification réelle.",
  "Repeated competition not computable: procedure not explicitly competitive, version conflict, missing identifier or contract outside the cohort.": "Concurrence répétée non calculable : procédure non explicitement concurrentielle, conflit de versions, identifiant manquant ou marché hors cohorte.",
  "Sufficient sample to examine concentration.": "Échantillon suffisant pour examiner la concentration.",
  "Concentration not computable: insufficient sample or coverage.": "Concentration non calculable : échantillon ou couverture insuffisants.",
  "Coverage thresholds met.": "Seuils de couverture atteints.",
  "Insufficient sample or coverage: no repetition indicator.": "Échantillon ou couverture insuffisants : pas d’indicateur de répétition.",
  "software CPV code": "code CPV logiciel",
  "software named in the object": "logiciel nommé dans l’objet",
  "award declared without competition": "attribution déclarée sans mise en concurrence",
  "article R2122-3 cited": "article R2122-3 cité",
  "procedure not classified, one offer received": "procédure non classée, une offre reçue",
  "Award history without dates: disqualifications not assessable.": "Historique des attributions sans dates : disqualifications non évaluables.",
  "Award without prior publication": "Attribution sans publication préalable",
  "Competitive procurement method published: exception rule out of scope.": "Méthode de passation concurrentielle publiée : règle d’exception hors champ.",
  "Contract changes are published in the separate contracting API, not imported: increase out of scope.": "Les modifications de contrat sont publiées dans l’API contrats distincte, non importée : hausse hors champ.",
  "Days added (dias_adicionados) not published for this row: applicability not established.": "Jours ajoutés (dias_adicionados) non publiés pour cette ligne : applicabilité non établie.",
  "Declared modality missing or outside the known SECOP II list: applicability not established.": "Modalité déclarée absente ou hors de la liste SECOP II connue : applicabilité non établie.",
  "Direct deal (trato directo)": "Gré à gré (trato directo)",
  "Direct modality: one tenderer is expected, not a signal.": "Modalité directe : un seul soumissionnaire est attendu, pas un signal.",
  "Diverging initial values: no increase calculation.": "Valeurs initiales divergentes : pas de calcul de hausse.",
  "Diverging modification values for the same identifier: no increase calculation.": "Valeurs de modification divergentes pour le même identifiant : pas de calcul de hausse.",
  "Duplicate identifier: calculation excluded.": "Identifiant en double : calcul exclu.",
  "Explicitly competitive modality (licitación, selección abreviada, subasta, concurso): this award-without-plurality rule is out of scope.": "Modalité explicitement concurrentielle (licitación, selección abreviada, subasta, concurso) : cette règle d’attribution sans pluralité est hors champ.",
  "Incomplete or inconsistent modification chronology.": "Chronologie des modifications incomplète ou incohérente.",
  "Initial amount or date unusable.": "Montant ou date initiale inexploitable.",
  "Insufficient sample or coverage: not assessed.": "Échantillon ou couverture insuffisants : non évalué.",
  "Negotiated procedure without competition": "Procédure négociée sans mise en concurrence",
  "Negotiated without prior publication": "Négociée sans publication préalable",
  "No better-ranked bid set aside before this award on this lot.": "Aucune offre mieux classée écartée avant cette attribution sur ce lot.",
  "No contract end date or duration is published in these records: duration out of scope.": "Ces enregistrements ne publient ni date de fin ni durée du contrat : durée hors champ.",
  "No eligible buyer/contract-type group for this holder: not assessed.": "Aucun groupe acheteur/type de contrat éligible pour ce titulaire : non évalué.",
  "No identified holder for a repetition computation.": "Aucun titulaire identifié pour calculer la répétition.",
  "No published amount amendment in the downloaded record. The absence of a published amendment does not prove the absence of a real change.": "Aucun avenant de montant publié dans l’enregistrement téléchargé. L’absence d’avenant publié ne prouve pas l’absence de changement réel.",
  "Number of offers for this lot not published.": "Nombre d’offres de ce lot non publié.",
  "Procedure code outside the known competitive/direct list: not assessed.": "Code de procédure hors de la liste concurrentielle/directe connue : non évalué.",
  "Procedure name not published: not assessed.": "Nom de la procédure non publié : non évalué.",
  "Procedure without competition: no ranking of bids.": "Procédure sans mise en concurrence : pas de classement des offres.",
  "Procedure without competition: one offer is expected, not a signal.": "Procédure sans mise en concurrence : une seule offre est attendue, pas un signal.",
  "Procurement method not published in this notice: not assessed.": "Méthode de passation non publiée dans cet avis : non évalué.",
  "Procurement method not published or outside the known OCDS list: applicability not established.": "Méthode de passation non publiée ou hors de la liste OCDS connue : applicabilité non établie.",
  "Procurement method not published: applicability not established.": "Méthode de passation non publiée : applicabilité non établie.",
  "Published justification of the modality missing: not assessable.": "Justification publiée de la modalité absente : non évaluable.",
  "Several declared holders: concentration of a single holder out of scope.": "Plusieurs titulaires déclarés : concentration d’un titulaire unique hors champ.",
  "Several different amounts on the same date.": "Plusieurs montants différents à la même date.",
  "Single-tenderer status unknown: repetition not assessable.": "Statut de soumissionnaire unique inconnu : répétition non évaluable.",
  "Supplier identifier missing: repetition not assessable.": "Identifiant du fournisseur absent : répétition non évaluable.",
  "Supplier identifier not usable (not a national registration number): repetition not assessable.": "Identifiant du fournisseur inexploitable (pas un numéro d’immatriculation national) : répétition non évaluable.",
  "Supplier identifier not usable: repetition not assessable.": "Identifiant du fournisseur inexploitable : répétition non évaluable.",
  "Supplier identity unknown: applicability not established.": "Identité du fournisseur inconnue : applicabilité non établie.",
  "The initial state of the history does not match the contract fields.": "L’état initial de l’historique ne correspond pas aux champs du marché.",
  "The last published modification does not state an amount.": "La dernière modification publiée n’indique pas de montant.",
  "This award is not a single-tenderer competitive award: outside the repetition scope.": "Cette attribution n’est pas concurrentielle à soumissionnaire unique : hors du champ de la répétition.",
  "This award is not declared by exception: outside the repetition scope.": "Cette attribution n’est pas déclarée par exception : hors du champ de la répétition.",
  "not specified": "non précisée",
  "Maintenance, support or licences of an existing software product placed with one vendor (docs/score-v3.md).": "Maintenance, support ou licences d’un logiciel existant confiés à un seul fournisseur (docs/score-v3.md).",
  "Agreement declared between public bodies (docs/score-colombia.md).": "Convention déclarée entre organismes publics (docs/score-colombia.md).",
  "Published amendments total 20 % of the original amount, the ceiling in Ley 7021/22 Art. 67 (docs/score-paraguay.md).": "Les avenants publiés totalisent 20 % du montant initial, le plafond de la Ley 7021/22 art. 67 (docs/score-paraguay.md).",
  "Explore published procurement records.": "Explorez les données publiées de la commande publique.",
  "Skip to results": "Aller aux résultats",
  "How to read · Method": "Comment lire · Méthode",
  "Theme:": "Thème :",
  "Auto": "Auto",
  "Light": "Clair",
  "Dark": "Sombre",
  "Signals only": "Signaux uniquement",
  "Import a dataset": "Importer un jeu de données",
  "Scope and limits": "Périmètre et limites",
  "A signal is a reason to look at a record, not evidence of wrongdoing. Missing data is shown as unknown, never as zero.": "Un signal est une raison d’examiner un enregistrement, pas la preuve d’une irrégularité. Les données manquantes sont affichées comme inconnues, jamais comme zéro.",
  "Paris & Ardèche — contracts · DECP": "Paris et Ardèche — marchés · DECP",
  "six cities — contracts · DECP": "six villes — marchés · DECP",
  "Tours — procurement notices · BOAMP/TED": "Tours — avis de marchés · BOAMP/TED",
  "3 Feb 2025 — consultation notices · BOAMP": "3 févr. 2025 — avis de consultation · BOAMP",
  "nationwide sample — award lots + audit dossiers · BOAMP/CRC": "échantillon national — lots attribués + dossiers de contrôle · BOAMP/CRC",
  "every dataset side by side (not merged, not summed)": "tous les jeux côte à côte (ni fusionnés, ni additionnés)",
  "MOP / Maule region / Puente Alto — licitaciones · Mercado Público": "MOP / région du Maule / Puente Alto — licitaciones · Mercado Público",
  "MEN / Caldas / Usaquén — contracts · SECOP II": "MEN / Caldas / Usaquén — contrats · SECOP II",
  "Finance / Moravian-Silesian region / Ostrava — award notices · TED": "Finances / région de Moravie-Silésie / Ostrava — avis d’attribution · TED",
  "Fernando de la Mora — contract records · DNCP OCDS": "Fernando de la Mora — fiches de contrats · DNCP OCDS",
  "MOPC / Central / Asunción — contract records · DNCP OCDS": "MOPC / Central / Asunción — fiches de contrats · DNCP OCDS",
  "IP / Cávado / Lisboa — award notices · TED": "IP / Cávado / Lisbonne — avis d’attribution · TED",
  "Finance / Cluj county / Cluj-Napoca — award notices · TED": "Finances / județ de Cluj / Cluj-Napoca — avis d’attribution · TED",
  "FCDO / Lincolnshire / Milton Keynes — award notices · Find a Tender": "FCDO / Lincolnshire / Milton Keynes — avis d’attribution · Find a Tender",
  "Health / Vinnytsia / Dnipro — contracts · Prozorro": "Santé / Vinnytsia / Dnipro — contrats · Prozorro",
  "Hide advanced filters": "Masquer les filtres avancés",
  "Filters": "Filtres",
  "Results": "Résultats",
  "Dataset overview": "Aperçu du jeu de données",
  "Signals": "Signaux",
  "Contract": "Contrat",
  "Your review": "Votre suivi",
  "Context outside the index": "Contexte hors indice",
  "Any index": "Tout indice",
  "Any": "Indifférent",
  "Review status": "État du suivi",
  "Not yet marked": "Pas encore marqué",
  "Any mark": "Toute marque",
  "Not marked": "Non marqué",
  "Follow up": "À suivre",
  "Referred": "Transmis",
  "Reviewed": "Examiné",
  "Stored in this browser only.": "Enregistré dans ce navigateur uniquement.",
  "None in this dataset yet.": "Aucune dans ce jeu de données pour l’instant.",
  "Export notes": "Exporter les notes",
  "Import notes": "Importer des notes",
  "Reset filters": "Réinitialiser les filtres",
  "Import method": "Mode d’import",
  "Browse only · no scoring": "Consultation seule · sans score",
  "French v3 checks · explicit opt-in": "Contrôles français v3 · activation explicite",
  "Dataset file (JSON, CSV or OCDS JSON)": "Fichier de données (JSON, CSV ou OCDS JSON)",
  "CSV works best with canonical headers such as": "Le CSV fonctionne mieux avec des en-têtes canoniques tels que",
  ", and": " et",
  ". OCDS JSON is also accepted. Files are read in this browser only, never uploaded.": ". OCDS JSON est aussi accepté. Les fichiers sont lus dans ce navigateur uniquement, jamais envoyés.",
  "Format details": "Détails du format",
  "Map CSV columns": "Associer les colonnes CSV",
  "Preview import": "Prévisualiser l’import",
  "Load previewed records": "Charger les enregistrements prévisualisés",
  "with the file picker in the filter panel, or serve this folder with": "avec le sélecteur de fichier du panneau de filtres, ou servez ce dossier avec",
  "Group": "Grouper",
  "Export all results:": "Exporter tous les résultats :",
  "Export all filtered records": "Exporter tous les enregistrements filtrés",
  "Buyer · Z–A": "Acheteur · Z–A",
  "Supplier · Z–A": "Titulaire · Z–A",
  "Offers · descending": "Offres · décroissant",
  "Sort by this column": "Trier par cette colonne",
  "Sorted descending · click for ascending": "Tri décroissant · cliquer pour croissant",
  "Sorted ascending · click for descending": "Tri croissant · cliquer pour décroissant",
  "Contracts and documented records — select a subject to open its details, evidence and sources.": "Marchés et enregistrements documentés — sélectionnez un objet pour ouvrir ses détails, pièces et sources.",
  "Vigilance index: an editorial review priority, not a probability": "Indice de vigilance : une priorité éditoriale d’examen, pas une probabilité",
  "Copy a short summary of this page with source URLs. Consider context before sharing.": "Copie un bref résumé de cette page avec les URL sources. Tenez compte du contexte avant de partager.",
  "Review notes stay in this browser; do not enter protected casework.": "Les notes de suivi restent dans ce navigateur ; n’y saisissez pas de dossiers protégés.",
  "Personal data in these records": "Données personnelles dans ces enregistrements",
  "Runs in your browser: no account, cookies, analytics or uploads. Always read the source document before drawing a conclusion.": "Fonctionne dans votre navigateur : ni compte, ni cookies, ni mesure d’audience, ni envoi de données. Lisez toujours le document source avant de conclure.",
  "‹ Previous": "‹ Précédent",
  "Next ›": "Suivant ›",
  "Print": "Imprimer",
  "Close": "Fermer",
  "Close details": "Fermer les détails",
  "Close (Esc)": "Fermer (Échap)",
  "Next record (j)": "Enregistrement suivant (j)",
  "Previous record (k)": "Enregistrement précédent (k)",
  "Print or save a case sheet for this record": "Imprimer ou enregistrer une fiche pour cet enregistrement",
  "Not in the current results": "Absent des résultats actuels",
  "Profile": "Profil",
  "All contracts of this buyer in the dataset": "Tous les marchés de cet acheteur dans le jeu de données",
  "All contracts of this supplier in the dataset": "Tous les marchés de ce titulaire dans le jeu de données",
  "Amount": "Montant",
  "Procedure": "Procédure",
  "Duration": "Durée",
  "Period start": "Début de période",
  "Published": "Publié",
  "months": "mois",
  "competitive": "concurrentielle",
  "without competition": "sans mise en concurrence",
  "not classified": "non classée",
  "active": "active",
  "ceased": "cessée",
  "status unknown": "état inconnu",
  "in the register on": "au registre le",
  "Note (stays in this browser)": "Note (reste dans ce navigateur)",
  "Saved": "Enregistré",
  "Not saved: storage blocked": "Non enregistré : stockage bloqué",
  "· not added (same family)": "· non ajouté (même famille)",
  "No threshold crossed in the evaluated checks.": "Aucun seuil franchi dans les contrôles évalués.",
  "Not assessed: no check could be evaluated.": "Non évalué : aucun contrôle n’a pu être évalué.",
  "competition": "concurrence",
  "execution": "exécution",
  "transparency": "transparence",
  "Details": "Détails",
  "Sources": "Sources",
  "Context · no points": "Contexte · sans points",
  "Lot": "Lot",
  "Notice": "Avis",
  "Notices": "Avis",
  "Buyer SIRET": "SIRET de l’acheteur",
  "Framework": "Accord-cadre",
  "Reference": "Référence",
  "Modalities": "Modalités",
  "Status": "Statut",
  "Call": "Appel",
  "Signed": "Signé",
  "Lots": "Lots",
  "Tender period (days)": "Délai de remise (jours)",
  "Category": "Catégorie",
  "Tender": "Appel d’offres",
  "Type": "Type",
  "Declared justification": "Justification déclarée",
  "Paid": "Payé",
  "Invoiced": "Facturé",
  "Price": "Prix",
  "Event": "Événement",
  "Notified": "Notifié",
  "Initial": "Initial",
  "Offers are counted on the whole tender, not per item.": "Les offres sont comptées sur l’ensemble de l’appel d’offres, pas par article.",
  "Finding scope: a set of orders examined by the CRC, not one award.": "Portée du constat : un ensemble de commandes examinées par la CRC, pas une attribution.",
  "Correction: deadline": "Rectificatif : date limite",
  "Previous notice": "Avis précédent",
  "Bid decisions": "Décisions sur les offres",
  "Award criteria (this lot)": "Critères d’attribution (ce lot)",
  "Procedure-wide text (may cover other lots):": "Texte portant sur toute la procédure (peut concerner d’autres lots) :",
  "Deadlines differ between sources.": "Les dates limites diffèrent selon les sources.",
  "Buyer document": "Document de l’acheteur",
  "Single-vendor software maintenance: often routine; exclusivity not verified.": "Maintenance logicielle auprès d’un seul éditeur : souvent courante ; exclusivité non vérifiée.",
  "Public-to-public agreement (declared interadministrative; not verified).": "Accord entre entités publiques (déclaré interadministratif ; non vérifié).",
  "No R2122 article cited in the published text.": "Aucun article R2122 cité dans le texte publié.",
  "Clear": "Sans signal",
  "Search the portal for": "Recherchez sur le portail",
  "None: fictional example.": "Aucune : exemple fictif.",
  "No source link published.": "Aucun lien source publié.",
  "Single offer": "Offre unique",
  "No competition": "Sans concurrence",
  "Repeated single offer": "Offre unique répétée",
  "Repeated no competition": "Sans concurrence répété",
  "Low competition rate": "Faible concurrence",
  "Concentration": "Concentration",
  "Better bid disqualified": "Meilleure offre écartée",
  "Late notice change": "Avis modifié tardivement",
  "Long duration": "Durée longue",
  "Amount increase": "Hausse du montant",
  "Term extended": "Durée prolongée",
  "Late publication": "Publication tardive",
  "Late notice change without deadline extension": "Modification tardive de l’avis sans report de la date limite"
 },
 "patterns": [
  [
   "{a} / {b} results · {c} with a heuristic signal · {d} not assessed",
   "{a} / {b} résultats · {c} avec un signal heuristique · {d} non évalués"
  ],
  [
   "{a} / {b} results · {c} with a heuristic signal · {d} not assessed · {e} advanced filter(s) active",
   "{a} / {b} résultats · {c} avec un signal heuristique · {d} non évalués · {e} filtre(s) avancé(s) actif(s)"
  ],
  [
   "Page {a} / {b} · {c} rows per page",
   "Page {a} / {b} · {c} lignes par page"
  ],
  [
   "Unable to load the data: {a}",
   "Impossible de charger les données : {a}"
  ],
  [
   "{a} page summaries copied. Review personal data before sharing.",
   "{a} résumés de page copiés. Vérifiez les données personnelles avant de partager."
  ],
  [
   "{a} filtered records exported as {b}.",
   "{a} enregistrements filtrés exportés en {b}."
  ],
  [
   "Context: {a}",
   "Contexte : {a}"
  ],
  [
   "Context: {a} · no points",
   "Contexte : {a} · sans points"
  ],
  [
   "Signals: {a}",
   "Signaux : {a}"
  ],
  [
   "{a} · current name ({b}), not historical",
   "{a} · nom actuel ({b}), non historique"
  ],
  [
   "Context · {a} cited · no points added",
   "Contexte · {a} cité · aucun point ajouté"
  ],
  [
   "{a} · Reference: {b}",
   "{a} · Référence : {b}"
  ],
  [
   "Buyer: {a} · Supplier: {b}",
   "Acheteur : {a} · Fournisseur : {b}"
  ],
  [
   "Procedure: {a} · Duration: {b}",
   "Procédure : {a} · Durée : {b}"
  ],
  [
   "Amount scope: {a}",
   "Portée du montant : {a}"
  ],
  [
   "Identifiers — Buyer SIRET: {a} · Contract: {b} · Lot: {c} · CPV: {d}",
   "Identifiants — SIRET acheteur : {a} · Marché : {b} · Lot : {c} · CPV : {d}"
  ],
  [
   "Notice: {a} · Publication: {b}",
   "Avis : {a} · Publication : {b}"
  ],
  [
   "Holders: {a}",
   "Titulaires : {a}"
  ],
  [
   "Heuristic index v{a} and coverage",
   "Indice heuristique v{a} et couverture"
  ],
  [
   "{a}/{b} checks with established applicability evaluated; {c} unknown applicabilities reported separately; {d} checks out of scope. The {e} checks are detailed below.",
   "{a}/{b} contrôles d’applicabilité établie évalués ; {c} applicabilités inconnues signalées à part ; {d} contrôles hors champ. Les {e} contrôles sont détaillés ci-dessous."
  ],
  [
   "Competition: {a} (maximum); execution/duration: {b} (maximum); transparency: {c} (maximum). Total: {d}/100. No compensation for unknown information.",
   "Concurrence : {a} (maximum) ; exécution/durée : {b} (maximum) ; transparence : {c} (maximum). Total : {d}/100. Aucune compensation pour l’information inconnue."
  ],
  [
   "{a} raw points",
   "{a} points bruts"
  ],
  [
   "raw weight {a}, family {b}",
   "poids brut {a}, famille {b}"
  ],
  [
   "also known as {a}",
   "aussi appelé {a}"
  ],
  [
   "If a link has moved, search the official portal for: {a}",
   "Si un lien a changé, cherchez sur le portail officiel : {a}"
  ],
  [
   "How this row was collected: {a} See “Sources and how to verify” above the table.",
   "Comment cette ligne a été collectée : {a} Voir « Sources et comment vérifier » au-dessus du tableau."
  ],
  [
   "Publisher: {a}. Licence: {b}.",
   "Éditeur : {a}. Licence : {b}."
  ],
  [
   "What was collected: {a}",
   "Ce qui a été collecté : {a}"
  ],
  [
   "Supplier document: {a}. A personal or tax identifier identifies the declared holder; it implies no suspicion and no link to other contracts by itself.",
   "Document du fournisseur : {a}. Un identifiant personnel ou fiscal identifie le titulaire déclaré ; il n’implique en soi ni soupçon ni lien avec d’autres contrats."
  ],
  [
   "Declared modality: {a} · Contract status: {b} · Contract type: {c}.",
   "Modalité déclarée : {a} · Statut du contrat : {b} · Type de contrat : {c}."
  ],
  [
   "Buyer profile · {a}",
   "Profil de l’acheteur · {a}"
  ],
  [
   "Supplier profile · {a}",
   "Profil du fournisseur · {a}"
  ],
  [
   "{a} contract(s) · {b} · {c} → {d} · {e} assessed · {f} with a signal ({g}). The table below now shows only these contracts. Compared with the {h} records of the same dataset; amounts are never summed.",
   "{a} marché(s) · {b} · {c} → {d} · {e} évalués · {f} avec un signal ({g}). Le tableau n’affiche plus que ces marchés. Comparé aux {h} enregistrements du même jeu ; les montants ne sont jamais additionnés."
  ],
  [
   "{a} contract(s) · {c} → {d} · {e} assessed · {f} with a signal ({g}). The table below now shows only these contracts. Compared with the {h} records of the same dataset; amounts are never summed.",
   "{a} marché(s) · {c} → {d} · {e} évalués · {f} avec un signal ({g}). Le tableau n’affiche plus que ces marchés. Comparé aux {h} enregistrements du même jeu ; les montants ne sont jamais additionnés."
  ],
  [
   "{a} / {b} evaluated ({c})",
   "{a} / {b} évalués ({c})"
  ],
  [
   "{a} of {b} evaluated",
   "{a} sur {b} évalués"
  ],
  [
   "{a} · {b} contract(s), {c} with a signal",
   "{a} · {b} marché(s), {c} avec un signal"
  ],
  [
   "Declared amounts: {a}. Not summed: declared amounts are not payments, and ceilings and amendments would double count.",
   "Montants déclarés : {a}. Non additionnés : les montants déclarés ne sont pas des paiements, et les plafonds et avenants seraient comptés deux fois."
  ],
  [
   "{a} day(s) added to a declared term of {b} months (+{c} %): not above +{d} %. Not a conclusion of regularity.",
   "{a} jour(s) ajouté(s) à une durée déclarée de {b} mois (+{c} %) : pas au-delà de +{d} %. Pas une conclusion de régularité."
  ],
  [
   "Same buyer and contract type ({a}): {b}/{c} contracts to this holder, out of {d} in the group ({e} % coverage). Minimum {f} identified contracts and {g} % coverage; from {h} points at {i} % to {j} at {k} %. Specialisation may explain a share; computed over the whole cohort, before filters.",
   "Même acheteur et type de contrat ({a}) : {b}/{c} contrats à ce titulaire, sur {d} dans le groupe ({e} % de couverture). Minimum {f} contrats identifiés et {g} % de couverture ; de {h} points à {i} % à {j} à {k} %. Une spécialisation peut expliquer une part ; calculé sur toute la cohorte, avant filtres."
  ],
  [
   "Non-competitive modality ({a}) with the published justification “{b}”: an ordinary declared ground in this cohort, not a plurality/urgency claim. Threshold not crossed — not a conclusion of regularity.",
   "Modalité non concurrentielle ({a}) avec la justification publiée « {b} » : un motif ordinaire déclaré dans cette cohorte, pas une invocation d’absence de pluralité ou d’urgence. Seuil non franchi — pas une conclusion de régularité."
  ],
  [
   "{a} months declared. From {b} months: {c} points, linear progression up to {d} at {e} months; renewals are not invented. Not a sectoral comparison nor an illegality threshold.",
   "{a} mois déclarés. À partir de {b} mois : {c} points, progression linéaire jusqu’à {d} à {e} mois ; les reconductions ne sont pas inventées. Ni une comparaison sectorielle, ni un seuil d’illégalité."
  ],
  [
   "{a} months declared (parsed read-only from “{b}”): below the {c}-month entry threshold. Not a conclusion of regularity.",
   "{a} mois déclarés (lus sans modification depuis « {b} ») : sous le seuil d’entrée de {c} mois. Pas une conclusion de régularité."
  ],
  [
   "{a} day(s) between the contract date ({b}) and the {c} ({d}): within {e} days. Not a conclusion of regularity.",
   "{a} jour(s) entre la date du contrat ({b}) et {c} ({d}) : dans les {e} jours. Pas une conclusion de régularité."
  ],
  [
   "{a} offer(s) declared, without presuming admissibility. One offer: {b} points, regardless of amount.",
   "{a} offre(s) déclarée(s), sans présumer leur recevabilité. Une offre : {b} points, quel que soit le montant."
  ],
  [
   "{a} offer(s) published for this lot ({b}). One offer: {c} points, all amounts. Admissibility is not assessed.",
   "{a} offre(s) publiée(s) pour ce lot ({b}). Une offre : {c} points, tous montants. La recevabilité n’est pas évaluée."
  ],
  [
   "Competitive procedure ({a}): no direct-award signal.",
   "Procédure concurrentielle ({a}) : pas de signal d’attribution directe."
  ],
  [
   "{a} days between the contract date ({b}) and the {c} ({d}). Above {e} days, beyond every legal deadline of the regimes covered: 8 points, linear to 16 at {f} days, in the transparency family. Late publication hides a contract from scrutiny while it runs; it can also be a clerical delay.",
   "{a} jours entre la date du contrat ({b}) et {c} ({d}). Au-delà de {e} jours, au-delà de tous les délais légaux des régimes couverts : 8 points, linéaire jusqu’à 16 à {f} jours, dans la famille transparence. Une publication tardive soustrait un marché au contrôle pendant son exécution ; ce peut aussi être un retard administratif."
  ],
  [
   "Publication date ({a}) before the contract date ({b}): inconsistent dates, not assessed.",
   "Date de publication ({a}) antérieure à la date du contrat ({b}) : dates incohérentes, non évalué."
  ],
  [
   "{a} days, upper bound. Signal if < 15 days; 8 points near 15, 40 at 3 days or fewer. Editorial threshold, not a legal one.",
   "{a} jours, borne haute. Signal si < 15 jours ; 8 points près de 15, 40 à 3 jours ou moins. Seuil éditorial, pas légal."
  ],
  [
   "Declared increase of {a} %. Signal strictly > 20 %, from 8 points near the threshold to 40 at +100 %. No euro threshold or bonus. Additional services possible: not a final expense nor a proven cost overrun.",
   "Hausse déclarée de {a} %. Signal strictement > 20 %, de 8 points près du seuil à 40 à +100 %. Ni seuil en euros ni bonus. Prestations supplémentaires possibles : ni une dépense finale, ni un surcoût prouvé."
  ],
  [
   "Same SIREN: {a}/{b} contracts to the known holder, out of {c} eligible; CPV {d}, 2024–2025. Minimum 10 and 80 % coverage. From 12 points at 60 % to 40 at 100 %. Specialisation and framework agreements may explain this share.",
   "Même SIREN : {a}/{b} marchés au titulaire connu, sur {c} éligibles ; CPV {d}, 2024–2025. Minimum 10 et 80 % de couverture. De 12 points à 60 % à 40 à 100 %. La spécialisation et les accords-cadres peuvent expliquer cette part."
  ],
  [
   "Same SIREN: {a}/{b} contracts to the known holder, out of {c} eligible; CPV {d}, 2024–2025. Minimum 10 and 80 % coverage. From 12 points at 60 % to 40 at 100 %. Specialisation and framework agreements may explain this share. Insufficient sample/coverage.",
   "Même SIREN : {a}/{b} marchés au titulaire connu, sur {c} éligibles ; CPV {d}, 2024–2025. Minimum 10 et 80 % de couverture. De 12 points à 60 % à 40 à 100 %. La spécialisation et les accords-cadres peuvent expliquer cette part. Échantillon ou couverture insuffisants."
  ],
  [
   "{a} direct awards identified, all amounts, same buyer/CPV/SIREN, 2024–2025. From 18 points at 3 contracts to 60 at 10. Unknown procedures do not become competitive. Legal exceptions possible.",
   "{a} attributions directes identifiées, tous montants, même acheteur/CPV/SIREN, 2024–2025. De 18 points à 3 marchés à 60 à 10. Les procédures inconnues ne deviennent pas concurrentielles. Exceptions légales possibles."
  ],
  [
   "Maintenance, support or licences of an existing software product ({a}), placed with one vendor ({b}). This is often routine: only the publisher or its appointed distributor can maintain its product. Proprietary status and exclusive rights are not verified here. No points added or removed; the index is unchanged.",
   "Maintenance, support ou licences d’un logiciel existant ({a}), confiés à un seul fournisseur ({b}). C’est souvent courant : seul l’éditeur ou son distributeur désigné peut maintenir son produit. Le caractère propriétaire et les droits exclusifs ne sont pas vérifiés ici. Aucun point ajouté ni retiré ; l’indice est inchangé."
  ],
  [
   "Price form: {a} · Type: {b}. Declared amounts, not observed payments.",
   "Forme du prix : {a} · Type : {b}. Montants déclarés, pas des paiements observés."
  ],
  [
   "Analysable declared evolution: +{a} (+{b} %), from {c} to {d}, on {e}. Quantities or scope may have changed; consult the source.",
   "Évolution déclarée analysable : +{a} (+{b} %), de {c} à {d}, le {e}. Les quantités ou le périmètre ont pu changer ; consultez la source."
  ],
  [
   "Increase calculation unavailable: {a}",
   "Calcul de la hausse indisponible : {a}"
  ],
  [
   "Single identified holder: SIREN {a}. Same buyer/CPV {b}, 2024–2025: {c}/{d} contracts to the known holder, out of {e} eligible contracts ({f} % coverage); {g} awards without competition identified to this holder, all amounts; {h}/{i} known competitive statuses. {j} The statistics do not change with your filters.",
   "Titulaire unique identifié : SIREN {a}. Même acheteur/CPV {b}, 2024–2025 : {c}/{d} marchés au titulaire connu, sur {e} marchés éligibles ({f} % de couverture) ; {g} attributions sans mise en concurrence identifiées à ce titulaire, tous montants ; {h}/{i} caractères concurrentiels connus. {j} Les statistiques ne changent pas avec vos filtres."
  ],
  [
   "Retrospective context {a}–{b}, same buyer and CPV {c}: {d} single-offer contracts / {e} with a known count, out of {f} eligible competitive contracts ({g} % coverage). {h} Computed over the whole cohort, unchanged by your filters.",
   "Contexte rétrospectif {a}–{b}, même acheteur et CPV {c} : {d} marchés à offre unique / {e} au nombre connu, sur {f} marchés concurrentiels éligibles ({g} % de couverture). {h} Calculé sur toute la cohorte, inchangé par vos filtres."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct procedure(s) in this cohort won with a single offer. From 12 points at 3, linear to 40 at 10.",
   "Même acheteur et fournisseur {a} : {b} procédure(s) distincte(s) de cette cohorte remportée(s) avec une seule offre. De 12 points à 3, linéaire jusqu’à 40 à 10."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct procedure(s) without competition in this cohort. From 18 points at 3, linear to 60 at 10. Lawful grounds may apply to each.",
   "Même acheteur et fournisseur {a} : {b} procédure(s) distincte(s) sans mise en concurrence dans cette cohorte. De 18 points à 3, linéaire jusqu’à 60 à 10. Chacune peut reposer sur un motif légal."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct process(es) in this cohort won as the only tenderer. From 12 points at {c}, linear to 40 at {d}. Computed over the whole cohort before filters.",
   "Même acheteur et fournisseur {a} : {b} procédure(s) distincte(s) de cette cohorte remportée(s) comme seul soumissionnaire. De 12 points à {c}, linéaire jusqu’à 40 à {d}. Calculé sur toute la cohorte avant filtres."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct process(es) awarded by exception in this cohort. From 18 points at {c}, linear to 60 at {d}. Lawful grounds may apply to each.",
   "Même acheteur et fournisseur {a} : {b} procédure(s) distincte(s) attribuée(s) par exception dans cette cohorte. De 18 points à {c}, linéaire jusqu’à 60 à {d}. Chacune peut reposer sur un motif légal."
  ],
  [
   "Same buyer and supplier document: {a} award(s) of this cohort declared without supplier plurality. From 18 points at {b} contracts, linear to 60 at {c}. Published declarations only; a lawful ground may still apply.",
   "Même acheteur et document du fournisseur : {a} attribution(s) de cette cohorte déclarée(s) sans pluralité d’offrants. De 18 points à {b} marchés, linéaire jusqu’à 60 à {c}. Déclarations publiées uniquement ; un motif légal peut s’appliquer."
  ],
  [
   "Same buyer and category {a}: {b}/{c} procedures won by this supplier, out of {d} ({e} % with an identified winner; lots of one procedure count once). Minimum 10 and 80 %; from 12 points at 60 % to 40 at 100 %. {f}",
   "Même acheteur et catégorie {a} : {b}/{c} procédures remportées par ce fournisseur, sur {d} ({e} % avec un attributaire identifié ; les lots d’une procédure comptent une fois). Minimum 10 et 80 % ; de 12 points à 60 % à 40 à 100 %. {f}"
  ],
  [
   "Same buyer and category {a}: {b}/{c} procedures won by this supplier, out of {d} ({e} % with an identified winner; lots of one procedure count once). Minimum 10 and 80 %; from 12 points at 60 % to 40 at 100 %.",
   "Même acheteur et catégorie {a} : {b}/{c} procédures remportées par ce fournisseur, sur {d} ({e} % avec un attributaire identifié ; les lots d’une procédure comptent une fois). Minimum 10 et 80 % ; de 12 points à 60 % à 40 à 100 %."
  ],
  [
   "{a} (OCDS procurementMethod limited): award without a competitive call. 18 points, all amounts. A lawful ground may apply (urgency, exclusivity, failed call); not assessed here.",
   "{a} (OCDS procurementMethod limited) : attribution sans appel à la concurrence. 18 points, tous montants. Un motif légal peut s’appliquer (urgence, exclusivité, appel infructueux) ; non évalué ici."
  ],
  [
   "{a} ({b}): award without a competitive call. 18 points, all amounts. A lawful ground may apply (urgency, exclusivity, failed call); not assessed here.",
   "{a} ({b}) : attribution sans appel à la concurrence. 18 points, tous montants. Un motif légal peut s’appliquer (urgence, exclusivité, appel infructueux) ; non évalué ici."
  ],
  [
   "{a} day(s) added to a declared term of {b} months (+{c} %). Strictly above +{d} %: 8 points, linear to 40 at +{e} %. Editorial threshold; an extension can be lawful and necessary (weather, design changes, budget calendars). Amount additions are not published in this extract.",
   "{a} jour(s) ajouté(s) à une durée déclarée de {b} mois (+{c} %). Strictement au-delà de +{d} % : 8 points, linéaire jusqu’à 40 à +{e} %. Seuil éditorial ; une prolongation peut être légale et nécessaire (météo, changements de conception, calendrier budgétaire). Les ajouts en valeur ne sont pas publiés dans cet extrait."
  ],
  [
   "{a} published amount amendment(s): +{b} % of the original declared amount. Signal strictly above 20 %, 8 points near the threshold to 40 at +100 %. Ley 7021/22 Art. 67 caps agreed modifications at 20 % of the original amount; DNCP rules allow a separate 20 % for unilateral public-interest changes (Art. 65 b), so a larger total is not by itself unlawful. Extra works or quantities may explain an increase; declared, not paid.",
   "{a} avenant(s) de montant publié(s) : +{b} % du montant initial déclaré. Signal strictement au-delà de 20 %, de 8 points près du seuil à 40 à +100 %. La Ley 7021/22 art. 67 plafonne les modifications convenues à 20 % du montant initial ; les règles de la DNCP autorisent 20 % supplémentaires pour des changements unilatéraux d’intérêt public (art. 65 b), donc un total supérieur n’est pas illégal en soi. Des travaux ou quantités supplémentaires peuvent expliquer une hausse ; déclaré, pas payé."
  ],
  [
   "{a} better-ranked bidder(s) on this lot had their award declared unsuccessful before this award. 12 points, all amounts. Disqualification is often lawful (missing documents, non-compliant offer); read the award decisions linked on the Prozorro page.",
   "{a} soumissionnaire(s) mieux classé(s) sur ce lot a/ont vu son/leur attribution déclarée infructueuse avant celle-ci. 12 points, tous montants. La disqualification est souvent légale (pièces manquantes, offre non conforme) ; lisez les décisions liées sur la page Prozorro."
  ],
  [
   "Award without competition ({a})",
   "Attribution sans mise en concurrence ({a})"
  ],
  [
   "Direct modality “{a}” without a declared exception: ordinary direct contracting adds no points. Not a conclusion of regularity.",
   "Modalité directe « {a} » sans exception déclarée : la contractation directe ordinaire n’ajoute aucun point. Pas une conclusion de régularité."
  ],
  [
   "Non-competitive modality ({a}) with the published justification “{b}”: the file itself declares an absent plurality of suppliers or manifest urgency. 18 points, all amounts. Ordinary grounds (professional services, interadministrative agreements, minimum-amount rules, regime statutes) add nothing; legality is not assessed here.",
   "Modalité non concurrentielle ({a}) avec la justification publiée « {b} » : le dossier déclare lui-même une absence de pluralité d’offrants ou une urgence manifeste. 18 points, tous montants. Les motifs ordinaires (services professionnels, conventions interadministratives, montant minimal, régimes spéciaux) n’ajoutent rien ; la légalité n’est pas évaluée ici."
  ],
  [
   "{a} months declared (parsed read-only from “{b}”). From {c} months: 8 points, linear to 40 at {d} months. Editorial threshold for this cohort, not a Colombian legal threshold; renewals are not invented.",
   "{a} mois déclarés (lus sans modification depuis « {b} »). À partir de {c} mois : 8 points, linéaire jusqu’à 40 à {d} mois. Seuil éditorial pour cette cohorte, pas un seuil légal colombien ; les reconductions ne sont pas inventées."
  ],
  [
   "Date: {a}",
   "Date : {a}"
  ],
  [
   "{a} — editorial index, not a probability nor legal gravity.",
   "{a} — indice éditorial, ni une probabilité ni une gravité juridique."
  ],
  [
   "{a} of {b} applicable checks evaluated.",
   "{a} contrôles applicables évalués sur {b}."
  ],
  [
   "{a} with unknown applicability.",
   "{a} d’applicabilité inconnue."
  ],
  [
   "All {a} checks",
   "Les {a} contrôles"
  ],
  [
   "Amendments ({a})",
   "Avenants ({a})"
  ],
  [
   "Change {a}",
   "Modification {a}"
  ],
  [
   "Amendments reach the legal 20 % ceiling (+{a} %).",
   "Les avenants atteignent le plafond légal de 20 % (+{a} %)."
  ],
  [
   "{a} complaint(s) filed on this tender.",
   "{a} recours déposé(s) sur cet appel d’offres."
  ],
  [
   "Joint purchase: {a}",
   "Achat groupé : {a}"
  ],
  [
   "Legal basis: {a}",
   "Base juridique : {a}"
  ],
  [
   "Bidding period not assessable: {a}",
   "Délai de remise non évaluable : {a}"
  ],
  [
   "Bidding period: {a} days (upper bound).",
   "Délai de remise : {a} jours (borne haute)."
  ],
  [
   "Conflicting initial versions ({a}): no chronology inferred.",
   "Versions initiales contradictoires ({a}) : aucune chronologie déduite."
  ],
  [
   "Official audit finding: {a}.",
   "Constat officiel de contrôle : {a}."
  ],
  [
   "Colour theme: {a} · click to change",
   "Thème de couleur : {a} · cliquer pour changer"
  ],
  [
   "Colour theme: {a}. Change theme.",
   "Thème de couleur : {a}. Changer de thème."
  ],
  [
   "Also known as {a}",
   "Aussi appelé {a}"
  ]
 ]
};
