// Generated by tools/i18n-strings.py from tools/i18n_table.py: edit the table, not this file.
window.I18N_DICTS = window.I18N_DICTS || {};
window.I18N_DICTS.es = {
 "title": "Contract signals — señales en contratos públicos",
 "exact": {
  "Language": "Idioma",
  "Interface language": "Idioma de la interfaz",
  "Contract signals": "Contract signals",
  "Explore published procurement records from France, Chile, Colombia, Czechia, Paraguay, Portugal, Romania, Ukraine and the United Kingdom.": "Explore registros publicados de contratación pública de Francia, Chile, Colombia, Chequia, Paraguay, Portugal, Rumanía, Ucrania y el Reino Unido.",
  "Runs entirely in your browser: no account, cookies, analytics or uploads. Filters live in the link after": "Funciona por completo en su navegador: sin cuenta, cookies, analítica ni envíos de datos. Los filtros se guardan en el enlace, después de",
  ", which browsers never send to a server; a chosen language is remembered in this browser only.": ", que los navegadores nunca envían a un servidor; el idioma elegido solo se recuerda en este navegador.",
  "Explore contracts": "Explorar contratos",
  "Dataset": "Conjunto de datos",
  "All countries": "Todos los países",
  "France": "Francia",
  "Chile": "Chile",
  "Colombia": "Colombia",
  "Czechia": "Chequia",
  "Paraguay": "Paraguay",
  "Portugal": "Portugal",
  "Romania": "Rumanía",
  "Ukraine": "Ucrania",
  "United Kingdom": "Reino Unido",
  "France · Paris & Ardèche — contracts · DECP": "Francia · París y Ardèche — contratos · DECP",
  "France · six cities — contracts · DECP": "Francia · seis ciudades — contratos · DECP",
  "France · Tours — procurement notices · BOAMP/TED": "Francia · Tours — anuncios de licitación · BOAMP/TED",
  "France · 3 Feb 2025 — consultation notices · BOAMP": "Francia · 3 feb. 2025 — anuncios de consulta · BOAMP",
  "France · nationwide sample — award lots + audit dossiers · BOAMP/CRC": "Francia · muestra nacional — lotes adjudicados + expedientes de auditoría · BOAMP/CRC",
  "All countries · every dataset side by side (not merged, not summed)": "Todos los países · todos los conjuntos lado a lado (sin fusionar ni sumar)",
  "Chile · MOP / Maule region / Puente Alto — licitaciones · Mercado Público": "Chile · MOP / Región del Maule / Puente Alto — licitaciones · Mercado Público",
  "Colombia · MEN / Caldas / Usaquén — contracts · SECOP II": "Colombia · MEN / Caldas / Usaquén — contratos · SECOP II",
  "Czechia · Finance / Moravian-Silesian region / Ostrava — award notices · TED": "Chequia · Finanzas / región de Moravia-Silesia / Ostrava — anuncios de adjudicación · TED",
  "Paraguay · Fernando de la Mora — contract records · DNCP OCDS": "Paraguay · Fernando de la Mora — registros de contratos · DNCP OCDS",
  "Paraguay · MOPC / Central / Asunción — contract records · DNCP OCDS": "Paraguay · MOPC / Central / Asunción — registros de contratos · DNCP OCDS",
  "Portugal · IP / Cávado / Lisboa — award notices · TED": "Portugal · IP / Cávado / Lisboa — anuncios de adjudicación · TED",
  "Romania · Finance / Cluj county / Cluj-Napoca — award notices · TED": "Rumanía · Finanzas / distrito de Cluj / Cluj-Napoca — anuncios de adjudicación · TED",
  "United Kingdom · FCDO / Lincolnshire / Milton Keynes — award notices · Find a Tender": "Reino Unido · FCDO / Lincolnshire / Milton Keynes — anuncios de adjudicación · Find a Tender",
  "Ukraine · Health / Vinnytsia / Dnipro — contracts · Prozorro": "Ucrania · Salud / Vínnytsia / Dnipró — contratos · Prozorro",
  "Search": "Buscar",
  "Buyer, supplier, subject, ID…": "Comprador, proveedor, objeto, identificador…",
  "Sort": "Ordenar",
  "Index · descending": "Índice · descendente",
  "Index · ascending": "Índice · ascendente",
  "Official findings first · outside the index": "Hallazgos oficiales primero · fuera del índice",
  "Amount · descending": "Monto · descendente",
  "Amount · ascending": "Monto · ascendente",
  "Signals · newest first": "Señales · más recientes primero",
  "Date · newest first": "Fecha · más reciente primero",
  "Date · oldest first": "Fecha · más antigua primero",
  "Notice publication · newest first": "Publicación del anuncio · más reciente primero",
  "Notice publication · oldest first": "Publicación del anuncio · más antigua primero",
  "CPV sector · A–Z": "Sector CPV · A–Z",
  "CPV sector · Z–A": "Sector CPV · Z–A",
  "Buyer · A–Z": "Comprador · A–Z",
  "Supplier · A–Z": "Proveedor · A–Z",
  "Offers · ascending": "Ofertas · ascendente",
  "Amount increase (%) · descending": "Aumento del monto (%) · descendente",
  "Indicators · most signals first": "Indicadores · más señales primero",
  "Indicators · fewest signals first": "Indicadores · menos señales primero",
  "Advanced filters": "Filtros avanzados",
  "Advanced search and filters": "Búsqueda y filtros avanzados",
  "Minimum amount": "Monto mínimo",
  "CPV purchase sector": "Sector de compra CPV",
  "All sectors": "Todos los sectores",
  "Group by": "Agrupar por",
  "No grouping": "Sin agrupar",
  "Documented project": "Proyecto documentado",
  "CPV sector": "Sector CPV",
  "Buyer": "Comprador",
  "Supplier (SIREN)": "Proveedor (SIREN)",
  "Project": "Proyecto",
  "All records": "Todos los registros",
  "Documented projects only": "Solo proyectos documentados",
  "Assessment": "Evaluación",
  "Not assessed / excluded": "No evaluado / excluido",
  "Partial coverage": "Cobertura parcial",
  "Zero after at least one evaluated check": "Cero tras al menos una verificación evaluada",
  "Minimum index": "Índice mínimo",
  "All indices": "Todos los índices",
  "20 and more": "20 o más",
  "40 and more": "40 o más",
  "70 and more": "70 o más",
  "Indicator": "Indicador",
  "All indicators": "Todos los indicadores",
  "Buyer with repeated low competition (France)": "Comprador con baja competencia repetida (Francia)",
  "Better-ranked bidder disqualified (Ukraine)": "Licitador mejor clasificado descalificado (Ucrania)",
  "Short bidding period (if assessable)": "Plazo de presentación corto (si es evaluable)",
  "Term extended after award (Colombia)": "Plazo prorrogado tras la adjudicación (Colombia)",
  "Published long after the contract (transparency)": "Publicado mucho después del contrato (transparencia)",
  "Official finding · outside the index": "Hallazgo oficial · fuera del índice",
  "Notice content · no points": "Contenido del anuncio · sin puntos",
  "Procedure text / published reason": "Texto del procedimiento / motivo publicado",
  "Award criteria present": "Criterios de adjudicación presentes",
  "Correction identified": "Corrección identificada",
  "Matched TED XML": "XML de TED asociado",
  "Legal context · no points": "Contexto jurídico · sin puntos",
  "All contexts": "Todos los contextos",
  "Declared without competition · all amounts": "Declarado sin competencia · todos los montos",
  "Article R2122 cited": "Artículo R2122 citado",
  "R2122-1 cited · imperative urgency": "R2122-1 citado · urgencia imperiosa",
  "R2122-3 cited · artistic, technical or exclusive-rights reasons": "R2122-3 citado · razones artísticas, técnicas o de derechos exclusivos",
  "Paraguay · amendments at the 20 % ceiling (Ley 7021 Art. 67)": "Paraguay · modificaciones en el tope del 20 % (Ley 7021 art. 67)",
  "Paraguay · complaint or investigation before the DNCP": "Paraguay · protesta o investigación ante la DNCP",
  "France · single-vendor software maintenance": "Francia · mantenimiento de software de un único proveedor",
  "Colombia · public-to-public agreement": "Colombia · convenio entre entidades públicas",
  "Show only heuristic signals": "Mostrar solo señales heurísticas",
  "Show only official audit findings": "Mostrar solo hallazgos oficiales de auditoría",
  "Show contract-linked final corruption judgments (if documented)": "Mostrar sentencias firmes por corrupción ligadas al contrato (si están documentadas)",
  "Show investigations reported at the time (current status unknown)": "Mostrar investigaciones informadas en su momento (estado actual desconocido)",
  "Clear advanced filters": "Borrar filtros avanzados",
  "Your browser may block automatic loading of a local file. Open": "Su navegador puede bloquear la carga automática de un archivo local. Abra",
  "with the file picker below, or serve this folder with": "con el selector de archivos de abajo, o sirva esta carpeta con",
  "Open your own JSON file": "Abrir su propio archivo JSON",
  "Read in this browser only, never uploaded.": "Se lee solo en este navegador; nunca se envía.",
  "File format": "Formato del archivo",
  "Signals prompt review, not accusations. A zero or missing label does not mean a contract is clean.": "Las señales invitan a revisar, no acusan. Un cero o la ausencia de etiqueta no significa que un contrato sea limpio.",
  "How to read these results ↓": "Cómo leer estos resultados ↓",
  "Loading data…": "Cargando datos…",
  "Export all filtered records:": "Exportar todos los registros filtrados:",
  "← Previous": "← Anterior",
  "Next →": "Siguiente →",
  "Rows/page": "Filas/página",
  "Copy page summary": "Copiar resumen de la página",
  "Table pagination": "Paginación de la tabla",
  "Copy a short summary of this page with source URLs. Check for personal data before pasting into an external service.": "Copia un breve resumen de esta página con las URL de las fuentes. Revise los datos personales antes de pegarlo en un servicio externo.",
  "Download every filtered record (all pages) as CSV. Built in your browser; nothing is uploaded.": "Descarga todos los registros filtrados (todas las páginas) en CSV. Se genera en su navegador; no se envía nada.",
  "Download every filtered record (all pages) as JSON, with the current view and caveats. Built in your browser; nothing is uploaded.": "Descarga todos los registros filtrados (todas las páginas) en JSON, con la vista actual y las advertencias. Se genera en su navegador; no se envía nada.",
  "Contracts and documented records — click a subject to open the details and history.": "Contratos y registros documentados: haga clic en un objeto para ver el detalle y el historial.",
  "Contracts table, horizontal scrolling possible": "Tabla de contratos, desplazamiento horizontal posible",
  "Date": "Fecha",
  "Supplier": "Proveedor",
  "Subject": "Objeto",
  "Declared amount": "Monto declarado",
  "Offers": "Ofertas",
  "Indicators": "Indicadores",
  "Index": "Índice",
  "Purchase sector, not the supplier’s NAF activity": "Sector de la compra, no la actividad del proveedor",
  "Declared financial stake, outside the index; not necessarily an expense": "Importe declarado, fuera del índice; no necesariamente un gasto",
  "Vigilance index": "Índice de vigilancia",
  "Vigilance scale, not a regularity measure": "Escala de vigilancia, no una medida de regularidad",
  "How to read the results": "Cómo leer los resultados",
  "Documented project dossier": "Expediente de proyecto documentado",
  "Buyer or supplier profile": "Perfil de comprador o proveedor",
  "Enable JavaScript to load and explore the data.": "Active JavaScript para cargar y explorar los datos.",
  "The indicators flag characteristics for review—not proof of irregularity, favoritism or corruption.": "Los indicadores señalan características a revisar; no prueban irregularidad, favoritismo ni corrupción.",
  "Public data can contain errors. A flag does not imply illegal behavior; no flag does not guarantee regularity. The copy button copies only summaries of the current page; large pages may exceed chat limits. Export CSV/JSON downloads every filtered record; an empty index cell means not assessed, not zero. Review personal data before pasting into any external service.": "Los datos públicos pueden contener errores. Una señal no implica una conducta ilegal; su ausencia no garantiza la regularidad. El botón de copia solo copia los resúmenes de la página actual; las páginas grandes pueden superar los límites de un chat. La exportación CSV/JSON descarga todos los registros filtrados; una celda de índice vacía significa «no evaluado», no cero. Revise los datos personales antes de pegarlos en un servicio externo.",
  "Data scope and limits": "Alcance y límites de los datos",
  "Exploratory 24-month history: 2,594 DECP contracts from Paris and Ardèche, notified in 2024–2025. Modifications published may be later than 2025. This is not a guarantee of exhaustiveness of actual purchases.": "Historial exploratorio de 24 meses: 2.594 contratos DECP de París y Ardèche, notificados en 2024–2025. Las modificaciones publicadas pueden ser posteriores a 2025. No garantiza la exhaustividad de las compras reales.",
  "Datasets are not merged; they may describe the same purchases. Do not add their amounts. “—” means unknown, not safe.": "Los conjuntos de datos no se fusionan; pueden describir las mismas compras. No sume sus montos. «—» significa desconocido, no seguro.",
  "Coverage and provenance (JSON)": "Cobertura y procedencia (JSON)",
  "Sources and how to verify": "Fuentes y cómo verificar",
  "Index and evidence labels": "Índice y etiquetas de evidencia",
  "0 · no threshold crossed in evaluated checks": "0 · ningún umbral superado en las verificaciones evaluadas",
  "1–19 · low": "1–19 · baja",
  "20–39 · moderate": "20–39 · moderada",
  "40–69 · high": "40–69 · alta",
  "70–100 · very high": "70–100 · muy alta",
  "Not assessed ≠ zero": "No evaluado ≠ cero",
  "Index v3.1 is an editorial sorting aid, not a probability; zero requires an evaluated check and certifies nothing. Unknowns are shown separately. Amounts and official findings never add points.": "El índice v3.1 es una ayuda editorial para ordenar, no una probabilidad; el cero exige una verificación evaluada y no certifica nada. Lo desconocido se muestra aparte. Los montos y los hallazgos oficiales nunca suman puntos.",
  "One French dossier has a dated news report of an investigative step; its current status is unknown. No comparable report is linked in the Colombian or Paraguayan pilots. No contract-specific final corruption judgment is documented in these datasets. French CRC audit observations are not convictions. No match means": "Un expediente francés cuenta con una noticia fechada sobre una diligencia de investigación; su estado actual se desconoce. No hay informe comparable en los pilotos de Colombia o Paraguay. Ninguna sentencia firme por corrupción ligada a un contrato está documentada en estos datos. Las observaciones de las CRC francesas no son condenas. La ausencia de coincidencia significa",
  "not established here, not cleared": "no establecido aquí, no descartado",
  "Method: vigilance index": "Método: índice de vigilancia",
  "Editorial choices, not calibrated to predict irregularity.": "Elecciones editoriales, no calibradas para predecir irregularidades.",
  "Comparison v2.1/v3 and ranking sensitivity (JSON)": "Comparación v2.1/v3 y sensibilidad del ranking (JSON)",
  ". Software verification is not legal or statistical validation. Flagged and unflagged cases must be reviewed.": ". La verificación del software no es una validación jurídica ni estadística. Deben revisarse los casos señalados y los no señalados.",
  "Full method and excerpt review": "Método completo y revisión de extractos",
  "Colombia pilot method": "Método del piloto de Colombia",
  "Countries proposed for upcoming pilots": "Países propuestos para próximos pilotos",
  "Source links must be kept. Every official finding must point to the document of the originating authority and to its relevant passage. Always consult the complete document and any responses from the organization concerned.": "Deben conservarse los enlaces a las fuentes. Todo hallazgo oficial debe remitir al documento de la autoridad de origen y a su pasaje pertinente. Consulte siempre el documento completo y las respuestas de la organización afectada.",
  "Version 3.1.": "Versión 3.1.",
  "Coverage:": "Cobertura:",
  "Weights:": "Pesos:",
  "SECOP II · Colombia pilot:": "SECOP II · piloto de Colombia:",
  "full method": "método completo",
  "Tours full notices:": "Anuncios completos de Tours:",
  "Six additional municipalities:": "Seis municipios adicionales:",
  "Short bidding period:": "Plazo de presentación corto:",
  "Concentrated awards:": "Adjudicaciones concentradas:",
  "Repeated direct awards:": "Adjudicaciones directas repetidas:",
  "Groupings:": "Agrupaciones:",
  "Published long after the contract (transparency):": "Publicado mucho después del contrato (transparencia):",
  "Declared amount increase:": "Aumento del monto declarado:",
  "Repeated low competition:": "Baja competencia repetida:",
  "Score = competition maximum (up to 60) + execution/duration maximum (up to 40) + transparency maximum (up to 16), capped at 100, with no renormalization by coverage, dataset or filter. Every check belongs to one indicator catalogue shared by all countries (": "Puntuación = máximo de competencia (hasta 60) + máximo de ejecución/duración (hasta 40) + máximo de transparencia (hasta 16), con tope de 100, sin renormalizar por cobertura, conjunto de datos o filtro. Cada verificación pertenece a un catálogo de indicadores común a todos los países (",
  "); eligibility and thresholds follow each jurisdiction. Official findings are separate documentary elements, never points. No amount-based uplift. No target proportion of flagged contracts.": "); la elegibilidad y los umbrales siguen cada jurisdicción. Los hallazgos oficiales son elementos documentales aparte, nunca puntos. Sin recargo por monto. Sin proporción objetivo de contratos señalados.",
  "Not assessed": "No evaluado",
  "Partial data": "Datos parciales",
  "No signal triggered": "Ninguna señal",
  "Low vigilance": "Vigilancia baja",
  "Moderate vigilance": "Vigilancia moderada",
  "High vigilance": "Vigilancia alta",
  "Very high vigilance": "Vigilancia muy alta",
  "Very high": "Muy alta",
  "High": "Alta",
  "Moderate": "Moderada",
  "Low": "Baja",
  "Documented · public source": "Documentado · fuente pública",
  "To verify · research lead": "Por verificar · pista de investigación",
  "Contract-period start · not signature": "Inicio del periodo del contrato · no la firma",
  "BOAMP publication": "Publicación BOAMP",
  "Ambiguous identifier / versions · calculations excluded": "Identificador / versiones ambiguos · cálculos excluidos",
  "Conflicting modification versions": "Versiones de modificación contradictorias",
  "Official audit finding · not a conviction": "Hallazgo oficial de auditoría · no es una condena",
  "Investigation reported at the time · current status unknown": "Investigación informada en su momento · estado actual desconocido",
  "Final judgment linked to this contract": "Sentencia firme ligada a este contrato",
  "unknown CPV": "CPV desconocido",
  "No result. Try lowering the minimum amount or changing the filters.": "Sin resultados. Pruebe a bajar el monto mínimo o a cambiar los filtros.",
  "every data/*.json file above": "todos los archivos data/*.json anteriores",
  "Single offer in a competitive procedure": "Oferta única en un procedimiento competitivo",
  "Award without competition": "Adjudicación sin competencia",
  "Repeated single-offer wins by the same supplier": "Adjudicaciones repetidas con oferta única al mismo proveedor",
  "Repeated awards without competition to the same supplier": "Adjudicaciones repetidas sin competencia al mismo proveedor",
  "Buyer with repeated low competition": "Comprador con baja competencia repetida",
  "Concentrated awards": "Adjudicaciones concentradas",
  "Better-ranked bidder disqualified": "Licitador mejor clasificado descalificado",
  "Short bidding period": "Plazo de presentación corto",
  "Long declared duration": "Duración declarada larga",
  "Amount increase after award": "Aumento del monto tras la adjudicación",
  "Term extended after award": "Plazo prorrogado tras la adjudicación",
  "Published long after the contract": "Publicado mucho después del contrato",
  "· competition": "· competencia",
  "· execution/duration": "· ejecución/duración",
  "· transparency": "· transparencia",
  "· competition · not added": "· competencia · no sumado",
  "· execution/duration · not added": "· ejecución/duración · no sumado",
  "· transparency · not added": "· transparencia · no sumado",
  "single-vendor software maintenance": "mantenimiento de software de un único proveedor",
  "public-to-public agreement": "convenio entre entidades públicas",
  "amendments at the 20 % ceiling": "modificaciones en el tope del 20 %",
  "Declared duration ≥ 10 years": "Duración declarada ≥ 10 años",
  "Relative increase in declared amount": "Aumento relativo del monto declarado",
  "Repeated low competition": "Baja competencia repetida",
  "Repeated direct awards": "Adjudicaciones directas repetidas",
  "Published more than 120 days after the contract": "Publicado más de 120 días después del contrato",
  "Award declared without supplier plurality or under manifest urgency": "Adjudicación declarada sin pluralidad de oferentes o por urgencia manifiesta",
  "Repeated awards declared without supplier plurality": "Adjudicaciones repetidas declaradas sin pluralidad de oferentes",
  "Concentrated awards within a contract type": "Adjudicaciones concentradas en un tipo de contrato",
  "Long declared duration (≥ 36 months)": "Duración declarada larga (≥ 36 meses)",
  "Declared term more than doubled by extensions (> 100 %)": "Plazo declarado más que duplicado por prórrogas (> 100 %)",
  "Single tenderer in a competitive procedure": "Oferente único en un procedimiento competitivo",
  "Award by exception to competitive procedure (CVE)": "Adjudicación por excepción al procedimiento competitivo (CVE)",
  "Repeated single-tenderer awards to the same supplier": "Adjudicaciones repetidas con oferente único al mismo proveedor",
  "Repeated exception awards to the same supplier": "Adjudicaciones repetidas por excepción al mismo proveedor",
  "Concentrated awards within a procurement category": "Adjudicaciones concentradas en una categoría de compra",
  "Declared amount increase > 20 %": "Aumento del monto declarado > 20 %",
  "Award without competition (Negotiated procedure without competition)": "Adjudicación sin competencia (procedimiento negociado sin competencia)",
  "Repeated single-offer awards to the same supplier": "Adjudicaciones repetidas con oferta única al mismo proveedor",
  "Concentrated awards within a category": "Adjudicaciones concentradas en una categoría",
  "Better-ranked bidder disqualified before the award": "Licitador mejor clasificado descalificado antes de la adjudicación",
  "Award without competition (Negotiated without prior publication)": "Adjudicación sin competencia (negociado sin publicación previa)",
  "Award without competition (Award without prior publication)": "Adjudicación sin competencia (adjudicación sin publicación previa)",
  "Award without competition (Direct deal (trato directo))": "Adjudicación sin competencia (trato directo)",
  "Signal": "Señal",
  "Evaluated · threshold not crossed": "Evaluado · umbral no superado",
  "Not assessable": "No evaluable",
  "Out of scope": "Fuera de alcance",
  "(unknown applicability)": "(aplicabilidad desconocida)",
  "Open procedure": "Procedimiento abierto",
  "Restricted procedure": "Procedimiento restringido",
  "Verify it yourself": "Verifíquelo usted mismo",
  "Buyer profile": "Perfil del comprador",
  "Supplier profile": "Perfil del proveedor",
  "Separate financial stake: the declared amount increases no weight. An increase uses only the comparable percentage, not a payments total. No points for an official finding, a project or an R2122 citation.": "Importe financiero aparte: el monto declarado no aumenta ningún peso. Un aumento usa solo el porcentaje comparable, no un total de pagos. Sin puntos por un hallazgo oficial, un proyecto o una cita del R2122.",
  "Not assessed: no applicable check could be evaluated. This is not a zero score.": "No evaluado: no se pudo evaluar ninguna verificación aplicable. No es una puntuación cero.",
  "No heuristic conclusion: not assessed. The documents and findings remain consultable.": "Sin conclusión heurística: no evaluado. Los documentos y hallazgos siguen consultables.",
  "No threshold crossed among the evaluated checks only. Unknowns do not prove an absence of risk.": "Ningún umbral superado entre las verificaciones evaluadas. Lo desconocido no prueba la ausencia de riesgo.",
  "Declared legal basis — context, not an indicator": "Base jurídica declarada — contexto, no un indicador",
  "Single-vendor software maintenance — context, not an indicator": "Mantenimiento de software de un único proveedor — contexto, no un indicador",
  "SECOP II — declared procedure and justification": "SECOP II — modalidad y justificación declaradas",
  "DNCP OCDS — published contract context": "DNCP OCDS — contexto publicado del contrato",
  "Published contract history": "Historial publicado del contrato",
  "Process page on the official portal: ": "Página del proceso en el portal oficial: ",
  "Current public identity — not historical": "Identidad pública actual — no histórica",
  "Documented official finding — separate from the index": "Hallazgo oficial documentado — separado del índice",
  "Reported investigation — separate from findings and index": "Investigación informada — separada de los hallazgos y del índice",
  "Paraguayan checks and their editorial thresholds: docs/score-paraguay.md. A signal is not a finding of irregularity.": "Verificaciones paraguayas y sus umbrales editoriales: docs/score-paraguay.md. Una señal no es un hallazgo de irregularidad.",
  "Exact queries, retrieval times, counts and exclusions (coverage JSON)": "Consultas exactas, fechas de obtención, recuentos y exclusiones (JSON de cobertura)",
  "To check one contract: open its row and follow “Verify it yourself”. Official pages come first; if a link has moved, search the portal for the identifiers listed there.": "Para comprobar un contrato: abra su fila y siga «Verifíquelo usted mismo». Las páginas oficiales van primero; si un enlace ha cambiado, busque en el portal los identificadores indicados.",
  "This buyer": "Este comprador",
  "This supplier": "Este proveedor",
  "Whole dataset": "Todo el conjunto",
  "not evaluated": "no evaluado",
  "Main suppliers": "Principales proveedores",
  "Main buyers": "Principales compradores",
  "A profile describes published declarations and heuristic signals only; a high rate is a reason to read the sources, not a finding.": "Un perfil describe solo declaraciones publicadas y señales heurísticas; una tasa alta es un motivo para leer las fuentes, no un hallazgo.",
  "Close profile and show all contracts": "Cerrar el perfil y mostrar todos los contratos",
  "This source publishes no publication date to compare with the contract date: out of scope.": "Esta fuente no publica una fecha de publicación comparable con la fecha del contrato: fuera de alcance.",
  "No offers/proposals table in this SECOP II extract: the number of offers was never imported; out of scope.": "Este extracto de SECOP II no tiene tabla de ofertas: el número de ofertas nunca se importó; fuera de alcance.",
  "No publication–deadline chronology in this extract: bidding period out of scope.": "Sin cronología publicación–plazo en este extracto: plazo de presentación fuera de alcance.",
  "Depends on offer counts, absent from this extract: repetition of low competition out of scope.": "Depende del número de ofertas, ausente en este extracto: repetición de baja competencia fuera de alcance.",
  "This contract is not among the awards declared without supplier plurality or under manifest urgency: outside the repetition scope.": "Este contrato no está entre las adjudicaciones declaradas sin pluralidad de oferentes o por urgencia manifiesta: fuera del alcance de la repetición.",
  "Initial notice and timetable not imported.": "Anuncio inicial y calendario no importados.",
  "Conflicting versions: calculations excluded.": "Versiones contradictorias: cálculos excluidos.",
  "Explicitly competitive procedure: no direct-award signal.": "Procedimiento explícitamente competitivo: sin señal de adjudicación directa.",
  "This contract is explicitly competitive: direct repetition out of scope.": "Este contrato es explícitamente competitivo: repetición directa fuera de alcance.",
  "This contract is not a single-offer competitive award: outside the repeated-single-offer scope.": "Este contrato no es una adjudicación competitiva con oferta única: fuera del alcance de la oferta única repetida.",
  "No duration threshold validated for this jurisdiction: out of scope.": "Ningún umbral de duración validado para esta jurisdicción: fuera de alcance.",
  "Not a single-offer competitive award: outside the repetition scope.": "No es una adjudicación competitiva con oferta única: fuera del alcance de la repetición.",
  "No validated minimum period for this jurisdiction in this method: out of scope.": "Ningún plazo mínimo validado para esta jurisdicción en este método: fuera de alcance.",
  "Single holder or insufficient/unknown cohort context; no name-based matching.": "Titular único o contexto de cohorte insuficiente/desconocido; sin cotejo por nombre.",
  "Published contract history not available for this record; increase check not applicable.": "Historial publicado del contrato no disponible para este registro; verificación de aumento no aplicable.",
  "Not an award without competition: outside the repetition scope.": "No es una adjudicación sin competencia: fuera del alcance de la repetición.",
  "No modification published in this extract; this does not prove the absence of an amendment.": "Ninguna modificación publicada en este extracto; esto no prueba la ausencia de una modificación.",
  "No eligible competitive context: no zero rate assumed.": "Sin contexto competitivo elegible: no se supone una tasa cero.",
  "An offer expected in a direct award adds nothing; competitive procedure not established if unknown.": "Una oferta esperada en una adjudicación directa no suma nada; procedimiento competitivo no establecido si se desconoce.",
  "Competitive character unknown.": "Carácter competitivo desconocido.",
  "Competitive character of this contract unknown: direct repetition not assessable.": "Carácter competitivo de este contrato desconocido: repetición directa no evaluable.",
  "Declared duration unknown.": "Duración declarada desconocida.",
  "Positive number of offers unknown or unusable.": "Número positivo de ofertas desconocido o inutilizable.",
  "Contract modification notices are separate TED notices, not imported: increase out of scope.": "Los anuncios de modificación son anuncios TED aparte, no importados: aumento fuera de alcance.",
  "Direct-contract report (reporting): ordinary, mostly low-value purchases recorded without a procedure; not scored, like the bare Colombian direct modality.": "Informe de contrato directo (reporting): compras ordinarias, sobre todo de bajo valor, registradas sin procedimiento; no puntuadas, como la modalidad directa colombiana.",
  "Contract change notices are separate Find a Tender notices, not imported: increase out of scope.": "Los anuncios de cambio de contrato son anuncios de Find a Tender aparte, no importados: aumento fuera de alcance.",
  "This source lists licitaciones only: direct deals (trato directo) are published as purchase orders, not imported. Out of scope, not clear.": "Esta fuente solo lista licitaciones: los tratos directos se publican como órdenes de compra, no importadas. Fuera de alcance, no descartado.",
  "Contract modifications are not in this OCDS source: increase out of scope.": "Las modificaciones del contrato no están en esta fuente OCDS: aumento fuera de alcance.",
  "Declared duration field missing: applicability not established.": "Campo de duración declarada ausente: aplicabilidad no establecida.",
  "Holder identity unknown: applicability not established.": "Identidad del titular desconocida: aplicabilidad no establecida.",
  "Supplier identity or category unknown: applicability not established.": "Identidad del proveedor o categoría desconocida: aplicabilidad no establecida.",
  "Unverified record: calculations excluded.": "Registro no verificado: cálculos excluidos.",
  "Duplicate contract identifier: calculations excluded.": "Identificador de contrato duplicado: cálculos excluidos.",
  "Not an individual awarded contract with a contract date.": "No es un contrato adjudicado individual con fecha de contrato.",
  "Contract date or publication date missing: delay not assessable.": "Falta la fecha del contrato o de publicación: retraso no evaluable.",
  "Find a Tender award notices can carry the date of an original contract signed years earlier (modification notices under PCR 2015 Regulation 72) or of admission to a dynamic purchasing system: the delay would not measure late publication. Out of scope.": "Los anuncios de adjudicación de Find a Tender pueden llevar la fecha de un contrato original firmado años antes (anuncios de modificación según el reglamento 72 de las PCR 2015) o de admisión a un sistema dinámico de adquisición: el retraso no mediría una publicación tardía. Fuera de alcance.",
  "Agriculture and fisheries": "Agricultura y pesca",
  "Energy and fuels": "Energía y combustibles",
  "Mining and minerals": "Minería y minerales",
  "Food and beverages": "Alimentos y bebidas",
  "Agricultural machinery": "Maquinaria agrícola",
  "Clothing and equipment": "Ropa y equipamiento",
  "Leather and textiles": "Cuero y textiles",
  "Printed matter and publishing": "Impresos y edición",
  "Chemical products": "Productos químicos",
  "Computer and office equipment": "Equipos informáticos y de oficina",
  "Electrical equipment": "Equipos eléctricos",
  "Telecommunications — equipment": "Telecomunicaciones — equipos",
  "Medical equipment and pharmacy": "Equipos médicos y farmacia",
  "Vehicles and transport — equipment": "Vehículos y transporte — equipos",
  "Security and defence — equipment": "Seguridad y defensa — equipos",
  "Music, sport and leisure — equipment": "Música, deporte y ocio — equipos",
  "Measurement, laboratory and optics": "Medición, laboratorio y óptica",
  "Furniture and miscellaneous equipment": "Mobiliario y equipos diversos",
  "Collected and purified water": "Agua captada y depurada",
  "Industrial machinery": "Maquinaria industrial",
  "Construction and mining machinery": "Maquinaria de construcción y minería",
  "Construction materials": "Materiales de construcción",
  "Construction work": "Obras de construcción",
  "Software": "Software",
  "Repair and maintenance": "Reparación y mantenimiento",
  "Installation": "Instalación",
  "Hotel and restaurant services": "Hostelería y restauración",
  "Transport": "Transporte",
  "Transport — ancillary services": "Transporte — servicios auxiliares",
  "Post and telecommunications": "Correos y telecomunicaciones",
  "Utility distribution services": "Distribución de suministros",
  "Finance and insurance": "Finanzas y seguros",
  "Real estate": "Inmobiliario",
  "Architecture, engineering and inspection": "Arquitectura, ingeniería e inspección",
  "IT services": "Servicios informáticos",
  "Research and development": "Investigación y desarrollo",
  "Administration, defence and social security": "Administración, defensa y seguridad social",
  "Oil and gas services": "Servicios de petróleo y gas",
  "Agricultural and forestry services": "Servicios agrícolas y forestales",
  "Consulting, communication and business services": "Consultoría, comunicación y servicios a empresas",
  "Education and training": "Educación y formación",
  "Health and social services": "Salud y servicios sociales",
  "Waste, sanitation and environment": "Residuos, saneamiento y medio ambiente",
  "Culture, leisure and sport": "Cultura, ocio y deporte",
  "Other services": "Otros servicios",
  "Sector not specified": "Sector no especificado",
  "essential data published on the buyer profile": "los datos esenciales publicados en el perfil del comprador",
  "BOAMP award notice": "el aviso de adjudicación del BOAMP",
  "TED award notice": "el aviso de adjudicación de TED",
  "Unreadable date: delay not assessable.": "Fecha ilegible: plazo no evaluable.",
  "Award explicitly declared without competition: 18 points, all amounts. May be legal; no bonus for an R2122 citation.": "Adjudicación declarada explícitamente sin competencia: 18 puntos, todos los montos. Puede ser legal; sin bonificación por citar el R2122.",
  "Rule reserved for explicitly open non-accelerated procedures; this record’s known type is out of scope.": "Regla reservada a los procedimientos abiertos explícitos no acelerados; el tipo conocido de este registro está fuera de alcance.",
  "No history for an identified holder: repetition unknown.": "Sin historial de un titular identificado: repetición desconocida.",
  "A citation proves neither that the legal conditions are met nor an irregularity. A single offer received does not demonstrate exclusivity. No points added; no inference about other contracts.": "Una cita no prueba ni que se cumplan las condiciones legales ni una irregularidad. Una sola oferta recibida no demuestra exclusividad. No se suman puntos; no se infiere nada sobre otros contratos.",
  "Article R2122 not found in the imported object or procedure. Justification unknown in this extract, not absence of justification.": "Artículo R2122 no encontrado en el objeto o el procedimiento importados. Justificación desconocida en este extracto, no ausencia de justificación.",
  "SIREN matching derived from an explicitly typed French identifier. Name and status of the legal unit observed at retrieval time, not those of each establishment nor those at the contract date. No points for the name or status; no link between companies inferred.": "Cotejo SIREN derivado de un identificador francés tipado explícitamente. Nombre y estado de la unidad legal observados en el momento de la consulta, no los de cada establecimiento ni los de la fecha del contrato. Sin puntos por el nombre o el estado; no se infiere vínculo entre empresas.",
  "Available published versions — absence of a published amendment ≠ absence of a real modification.": "Versiones publicadas disponibles — la ausencia de una modificación publicada ≠ ausencia de una modificación real.",
  "Repeated competition not computable: procedure not explicitly competitive, version conflict, missing identifier or contract outside the cohort.": "Competencia repetida no calculable: procedimiento no explícitamente competitivo, conflicto de versiones, identificador ausente o contrato fuera de la cohorte.",
  "Sufficient sample to examine concentration.": "Muestra suficiente para examinar la concentración.",
  "Concentration not computable: insufficient sample or coverage.": "Concentración no calculable: muestra o cobertura insuficiente.",
  "Coverage thresholds met.": "Umbrales de cobertura alcanzados.",
  "Insufficient sample or coverage: no repetition indicator.": "Muestra o cobertura insuficiente: sin indicador de repetición.",
  "software CPV code": "código CPV de software",
  "software named in the object": "software nombrado en el objeto",
  "award declared without competition": "adjudicación declarada sin competencia",
  "article R2122-3 cited": "artículo R2122-3 citado",
  "procedure not classified, one offer received": "procedimiento no clasificado, una oferta recibida",
  "Award history without dates: disqualifications not assessable.": "Historial de adjudicaciones sin fechas: descalificaciones no evaluables.",
  "Award without prior publication": "Adjudicación sin publicación previa",
  "Competitive procurement method published: exception rule out of scope.": "Método de contratación competitivo publicado: regla de excepción fuera de alcance.",
  "Contract changes are published in the separate contracting API, not imported: increase out of scope.": "Los cambios de contrato se publican en la API de contratos aparte, no importada: aumento fuera de alcance.",
  "Days added (dias_adicionados) not published for this row: applicability not established.": "Días adicionados (dias_adicionados) no publicados para esta fila: aplicabilidad no establecida.",
  "Declared modality missing or outside the known SECOP II list: applicability not established.": "Modalidad declarada ausente o fuera de la lista conocida de SECOP II: aplicabilidad no establecida.",
  "Direct deal (trato directo)": "Trato directo",
  "Direct modality: one tenderer is expected, not a signal.": "Modalidad directa: se espera un solo oferente, no es una señal.",
  "Diverging initial values: no increase calculation.": "Valores iniciales divergentes: sin cálculo de aumento.",
  "Diverging modification values for the same identifier: no increase calculation.": "Valores de modificación divergentes para el mismo identificador: sin cálculo de aumento.",
  "Duplicate identifier: calculation excluded.": "Identificador duplicado: cálculo excluido.",
  "Explicitly competitive modality (licitación, selección abreviada, subasta, concurso): this award-without-plurality rule is out of scope.": "Modalidad explícitamente competitiva (licitación, selección abreviada, subasta, concurso): esta regla de adjudicación sin pluralidad está fuera de alcance.",
  "Incomplete or inconsistent modification chronology.": "Cronología de modificaciones incompleta o incoherente.",
  "Initial amount or date unusable.": "Monto o fecha inicial inutilizable.",
  "Insufficient sample or coverage: not assessed.": "Muestra o cobertura insuficiente: no evaluado.",
  "Negotiated procedure without competition": "Procedimiento negociado sin competencia",
  "Negotiated without prior publication": "Negociado sin publicación previa",
  "No better-ranked bid set aside before this award on this lot.": "Ninguna oferta mejor clasificada descartada antes de esta adjudicación en este lote.",
  "No contract end date or duration is published in these records: duration out of scope.": "Estos registros no publican fecha de fin ni duración del contrato: duración fuera de alcance.",
  "No eligible buyer/contract-type group for this holder: not assessed.": "Ningún grupo comprador/tipo de contrato elegible para este titular: no evaluado.",
  "No identified holder for a repetition computation.": "Ningún titular identificado para calcular la repetición.",
  "No published amount amendment in the downloaded record. The absence of a published amendment does not prove the absence of a real change.": "Ninguna modificación de monto publicada en el registro descargado. La ausencia de una modificación publicada no prueba la ausencia de un cambio real.",
  "Number of offers for this lot not published.": "Número de ofertas de este lote no publicado.",
  "Procedure code outside the known competitive/direct list: not assessed.": "Código de procedimiento fuera de la lista conocida competitiva/directa: no evaluado.",
  "Procedure name not published: not assessed.": "Nombre del procedimiento no publicado: no evaluado.",
  "Procedure without competition: no ranking of bids.": "Procedimiento sin competencia: sin clasificación de ofertas.",
  "Procedure without competition: one offer is expected, not a signal.": "Procedimiento sin competencia: se espera una sola oferta, no es una señal.",
  "Procurement method not published in this notice: not assessed.": "Método de contratación no publicado en este aviso: no evaluado.",
  "Procurement method not published or outside the known OCDS list: applicability not established.": "Método de contratación no publicado o fuera de la lista OCDS conocida: aplicabilidad no establecida.",
  "Procurement method not published: applicability not established.": "Método de contratación no publicado: aplicabilidad no establecida.",
  "Published justification of the modality missing: not assessable.": "Justificación publicada de la modalidad ausente: no evaluable.",
  "Several declared holders: concentration of a single holder out of scope.": "Varios titulares declarados: concentración de un titular único fuera de alcance.",
  "Several different amounts on the same date.": "Varios montos distintos en la misma fecha.",
  "Single-tenderer status unknown: repetition not assessable.": "Situación de oferente único desconocida: repetición no evaluable.",
  "Supplier identifier missing: repetition not assessable.": "Identificador del proveedor ausente: repetición no evaluable.",
  "Supplier identifier not usable (not a national registration number): repetition not assessable.": "Identificador del proveedor inutilizable (no es un número de registro nacional): repetición no evaluable.",
  "Supplier identifier not usable: repetition not assessable.": "Identificador del proveedor inutilizable: repetición no evaluable.",
  "Supplier identity unknown: applicability not established.": "Identidad del proveedor desconocida: aplicabilidad no establecida.",
  "The initial state of the history does not match the contract fields.": "El estado inicial del historial no coincide con los campos del contrato.",
  "The last published modification does not state an amount.": "La última modificación publicada no indica un monto.",
  "This award is not a single-tenderer competitive award: outside the repetition scope.": "Esta adjudicación no es competitiva con oferente único: fuera del alcance de la repetición.",
  "This award is not declared by exception: outside the repetition scope.": "Esta adjudicación no se declara por excepción: fuera del alcance de la repetición.",
  "not specified": "no especificada",
  "Maintenance, support or licences of an existing software product placed with one vendor (docs/score-v3.md).": "Mantenimiento, soporte o licencias de un producto de software existente contratado con un único proveedor (docs/score-v3.md).",
  "Agreement declared between public bodies (docs/score-colombia.md).": "Convenio declarado entre entidades públicas (docs/score-colombia.md).",
  "Published amendments total 20 % of the original amount, the ceiling in Ley 7021/22 Art. 67 (docs/score-paraguay.md).": "Las modificaciones publicadas suman el 20 % del monto original, el tope de la Ley 7021/22 Art. 67 (docs/score-paraguay.md).",
  "Explore published procurement records.": "Explore registros publicados de contratación pública.",
  "Skip to results": "Ir a los resultados",
  "How to read · Method": "Cómo leer · Método",
  "Theme:": "Tema:",
  "Auto": "Auto",
  "Light": "Claro",
  "Dark": "Oscuro",
  "Signals only": "Solo señales",
  "Import a dataset": "Importar un conjunto de datos",
  "Scope and limits": "Alcance y límites",
  "A signal is a reason to look at a record, not evidence of wrongdoing. Missing data is shown as unknown, never as zero.": "Una señal es un motivo para examinar un registro, no una prueba de irregularidad. Los datos faltantes se muestran como desconocidos, nunca como cero.",
  "Paris & Ardèche — contracts · DECP": "París y Ardèche — contratos · DECP",
  "six cities — contracts · DECP": "seis ciudades — contratos · DECP",
  "Tours — procurement notices · BOAMP/TED": "Tours — anuncios de licitación · BOAMP/TED",
  "3 Feb 2025 — consultation notices · BOAMP": "3 feb. 2025 — anuncios de consulta · BOAMP",
  "nationwide sample — award lots + audit dossiers · BOAMP/CRC": "muestra nacional — lotes adjudicados + expedientes de auditoría · BOAMP/CRC",
  "every dataset side by side (not merged, not summed)": "todos los conjuntos lado a lado (sin fusionar ni sumar)",
  "MOP / Maule region / Puente Alto — licitaciones · Mercado Público": "MOP / Región del Maule / Puente Alto — licitaciones · Mercado Público",
  "MEN / Caldas / Usaquén — contracts · SECOP II": "MEN / Caldas / Usaquén — contratos · SECOP II",
  "Finance / Moravian-Silesian region / Ostrava — award notices · TED": "Finanzas / región de Moravia-Silesia / Ostrava — anuncios de adjudicación · TED",
  "Fernando de la Mora — contract records · DNCP OCDS": "Fernando de la Mora — registros de contratos · DNCP OCDS",
  "MOPC / Central / Asunción — contract records · DNCP OCDS": "MOPC / Central / Asunción — registros de contratos · DNCP OCDS",
  "IP / Cávado / Lisboa — award notices · TED": "IP / Cávado / Lisboa — anuncios de adjudicación · TED",
  "Finance / Cluj county / Cluj-Napoca — award notices · TED": "Finanzas / distrito de Cluj / Cluj-Napoca — anuncios de adjudicación · TED",
  "FCDO / Lincolnshire / Milton Keynes — award notices · Find a Tender": "FCDO / Lincolnshire / Milton Keynes — anuncios de adjudicación · Find a Tender",
  "Health / Vinnytsia / Dnipro — contracts · Prozorro": "Salud / Vínnytsia / Dnipró — contratos · Prozorro",
  "Hide advanced filters": "Ocultar filtros avanzados",
  "Filters": "Filtros",
  "Results": "Resultados",
  "Dataset overview": "Resumen del conjunto de datos",
  "Signals": "Señales",
  "Contract": "Contrato",
  "Your review": "Su revisión",
  "Context outside the index": "Contexto fuera del índice",
  "Any index": "Cualquier índice",
  "Any": "Cualquiera",
  "Review status": "Estado de revisión",
  "Not yet marked": "Aún sin marcar",
  "Any mark": "Cualquier marca",
  "Not marked": "Sin marcar",
  "Follow up": "Dar seguimiento",
  "Referred": "Remitido",
  "Reviewed": "Revisado",
  "Stored in this browser only.": "Guardado solo en este navegador.",
  "None in this dataset yet.": "Ninguna en este conjunto de datos por ahora.",
  "Export notes": "Exportar notas",
  "Import notes": "Importar notas",
  "Reset filters": "Restablecer filtros",
  "Import method": "Método de importación",
  "Browse only · no scoring": "Solo consulta · sin puntuación",
  "French v3 checks · explicit opt-in": "Controles franceses v3 · activación explícita",
  "Dataset file (JSON, CSV or OCDS JSON)": "Archivo de datos (JSON, CSV u OCDS JSON)",
  "CSV works best with canonical headers such as": "El CSV funciona mejor con encabezados canónicos como",
  ", and": " y",
  ". OCDS JSON is also accepted. Files are read in this browser only, never uploaded.": ". También se acepta OCDS JSON. Los archivos se leen solo en este navegador y nunca se envían.",
  "Format details": "Detalles del formato",
  "Map CSV columns": "Asignar columnas CSV",
  "Preview import": "Previsualizar la importación",
  "Load previewed records": "Cargar los registros previsualizados",
  "with the file picker in the filter panel, or serve this folder with": "con el selector de archivos del panel de filtros, o sirva esta carpeta con",
  "Group": "Agrupar",
  "Export all results:": "Exportar todos los resultados:",
  "Export all filtered records": "Exportar todos los registros filtrados",
  "Buyer · Z–A": "Comprador · Z–A",
  "Supplier · Z–A": "Proveedor · Z–A",
  "Offers · descending": "Ofertas · descendente",
  "Sort by this column": "Ordenar por esta columna",
  "Sorted descending · click for ascending": "Orden descendente · clic para ascendente",
  "Sorted ascending · click for descending": "Orden ascendente · clic para descendente",
  "Contracts and documented records — select a subject to open its details, evidence and sources.": "Contratos y registros documentados — seleccione un objeto para abrir sus detalles, pruebas y fuentes.",
  "Vigilance index: an editorial review priority, not a probability": "Índice de vigilancia: una prioridad editorial de revisión, no una probabilidad",
  "Copy a short summary of this page with source URLs. Consider context before sharing.": "Copia un resumen breve de esta página con las URL de origen. Considere el contexto antes de compartir.",
  "Review notes stay in this browser; do not enter protected casework.": "Las notas de revisión permanecen en este navegador; no introduzca expedientes protegidos.",
  "Personal data in these records": "Datos personales en estos registros",
  "Runs in your browser: no account, cookies, analytics or uploads. Always read the source document before drawing a conclusion.": "Funciona en su navegador: sin cuenta, cookies, analítica ni envíos de datos. Lea siempre el documento de origen antes de sacar una conclusión.",
  "‹ Previous": "‹ Anterior",
  "Next ›": "Siguiente ›",
  "Print": "Imprimir",
  "Close": "Cerrar",
  "Close details": "Cerrar los detalles",
  "Close (Esc)": "Cerrar (Esc)",
  "Next record (j)": "Registro siguiente (j)",
  "Previous record (k)": "Registro anterior (k)",
  "Print or save a case sheet for this record": "Imprimir o guardar una ficha de este registro",
  "Not in the current results": "No está en los resultados actuales",
  "Profile": "Perfil",
  "All contracts of this buyer in the dataset": "Todos los contratos de este comprador en el conjunto de datos",
  "All contracts of this supplier in the dataset": "Todos los contratos de este proveedor en el conjunto de datos",
  "Amount": "Importe",
  "Procedure": "Procedimiento",
  "Duration": "Duración",
  "Period start": "Inicio del período",
  "Published": "Publicado",
  "months": "meses",
  "competitive": "competitivo",
  "without competition": "sin competencia",
  "not classified": "sin clasificar",
  "active": "activa",
  "ceased": "cesada",
  "status unknown": "estado desconocido",
  "in the register on": "en el registro el",
  "Note (stays in this browser)": "Nota (permanece en este navegador)",
  "Saved": "Guardado",
  "Not saved: storage blocked": "No guardado: almacenamiento bloqueado",
  "· not added (same family)": "· no sumado (misma familia)",
  "No threshold crossed in the evaluated checks.": "Ningún umbral superado en los controles evaluados.",
  "Not assessed: no check could be evaluated.": "No evaluado: no se pudo evaluar ningún control.",
  "competition": "competencia",
  "execution": "ejecución",
  "transparency": "transparencia",
  "Details": "Detalles",
  "Sources": "Fuentes",
  "Context · no points": "Contexto · sin puntos",
  "Lot": "Lote",
  "Notice": "Anuncio",
  "Notices": "Anuncios",
  "Buyer SIRET": "SIRET del comprador",
  "Framework": "Acuerdo marco",
  "Reference": "Referencia",
  "Modalities": "Modalidades",
  "Status": "Estado",
  "Call": "Convocatoria",
  "Signed": "Firmado",
  "Lots": "Lotes",
  "Tender period (days)": "Plazo de oferta (días)",
  "Category": "Categoría",
  "Tender": "Licitación",
  "Type": "Tipo",
  "Declared justification": "Justificación declarada",
  "Paid": "Pagado",
  "Invoiced": "Facturado",
  "Price": "Precio",
  "Event": "Evento",
  "Notified": "Notificado",
  "Initial": "Inicial",
  "Offers are counted on the whole tender, not per item.": "Las ofertas se cuentan para toda la licitación, no por ítem.",
  "Finding scope: a set of orders examined by the CRC, not one award.": "Alcance del hallazgo: un conjunto de pedidos examinados por la CRC, no una adjudicación.",
  "Correction: deadline": "Rectificación: plazo",
  "Previous notice": "Anuncio anterior",
  "Bid decisions": "Decisiones sobre las ofertas",
  "Award criteria (this lot)": "Criterios de adjudicación (este lote)",
  "Procedure-wide text (may cover other lots):": "Texto de todo el procedimiento (puede abarcar otros lotes):",
  "Deadlines differ between sources.": "Los plazos difieren entre las fuentes.",
  "Buyer document": "Documento del comprador",
  "Single-vendor software maintenance: often routine; exclusivity not verified.": "Mantenimiento de software con un solo proveedor: a menudo rutinario; exclusividad no verificada.",
  "Public-to-public agreement (declared interadministrative; not verified).": "Convenio entre entidades públicas (declarado interadministrativo; no verificado).",
  "No R2122 article cited in the published text.": "Ningún artículo R2122 citado en el texto publicado.",
  "Clear": "Sin señal",
  "Search the portal for": "Busque en el portal",
  "None: fictional example.": "Ninguna: ejemplo ficticio.",
  "No source link published.": "No se publicó ningún enlace de origen.",
  "Single offer": "Oferta única",
  "No competition": "Sin competencia",
  "Repeated single offer": "Oferta única repetida",
  "Repeated no competition": "Sin competencia repetida",
  "Low competition rate": "Baja competencia",
  "Concentration": "Concentración",
  "Better bid disqualified": "Mejor oferta descalificada",
  "Late notice change": "Cambio tardío del anuncio",
  "Long duration": "Duración larga",
  "Amount increase": "Aumento del importe",
  "Term extended": "Plazo ampliado",
  "Late publication": "Publicación tardía",
  "Late notice change without deadline extension": "Cambio tardío del anuncio sin prórroga del plazo"
 },
 "patterns": [
  [
   "{a} / {b} results · {c} with a heuristic signal · {d} not assessed",
   "{a} / {b} resultados · {c} con señal heurística · {d} no evaluados"
  ],
  [
   "{a} / {b} results · {c} with a heuristic signal · {d} not assessed · {e} advanced filter(s) active",
   "{a} / {b} resultados · {c} con señal heurística · {d} no evaluados · {e} filtro(s) avanzado(s) activo(s)"
  ],
  [
   "Page {a} / {b} · {c} rows per page",
   "Página {a} / {b} · {c} filas por página"
  ],
  [
   "Unable to load the data: {a}",
   "No se pudieron cargar los datos: {a}"
  ],
  [
   "{a} page summaries copied. Review personal data before sharing.",
   "{a} resúmenes de página copiados. Revise los datos personales antes de compartir."
  ],
  [
   "{a} filtered records exported as {b}.",
   "{a} registros filtrados exportados en {b}."
  ],
  [
   "Context: {a}",
   "Contexto: {a}"
  ],
  [
   "Context: {a} · no points",
   "Contexto: {a} · sin puntos"
  ],
  [
   "Signals: {a}",
   "Señales: {a}"
  ],
  [
   "{a} · current name ({b}), not historical",
   "{a} · nombre actual ({b}), no histórico"
  ],
  [
   "Context · {a} cited · no points added",
   "Contexto · {a} citado · sin puntos"
  ],
  [
   "{a} · Reference: {b}",
   "{a} · Referencia: {b}"
  ],
  [
   "Buyer: {a} · Supplier: {b}",
   "Comprador: {a} · Proveedor: {b}"
  ],
  [
   "Procedure: {a} · Duration: {b}",
   "Procedimiento: {a} · Duración: {b}"
  ],
  [
   "Amount scope: {a}",
   "Alcance del monto: {a}"
  ],
  [
   "Identifiers — Buyer SIRET: {a} · Contract: {b} · Lot: {c} · CPV: {d}",
   "Identificadores — SIRET del comprador: {a} · Contrato: {b} · Lote: {c} · CPV: {d}"
  ],
  [
   "Notice: {a} · Publication: {b}",
   "Anuncio: {a} · Publicación: {b}"
  ],
  [
   "Holders: {a}",
   "Titulares: {a}"
  ],
  [
   "Heuristic index v{a} and coverage",
   "Índice heurístico v{a} y cobertura"
  ],
  [
   "{a}/{b} checks with established applicability evaluated; {c} unknown applicabilities reported separately; {d} checks out of scope. The {e} checks are detailed below.",
   "{a}/{b} verificaciones con aplicabilidad establecida evaluadas; {c} aplicabilidades desconocidas indicadas aparte; {d} verificaciones fuera de alcance. Las {e} verificaciones se detallan abajo."
  ],
  [
   "Competition: {a} (maximum); execution/duration: {b} (maximum); transparency: {c} (maximum). Total: {d}/100. No compensation for unknown information.",
   "Competencia: {a} (máximo); ejecución/duración: {b} (máximo); transparencia: {c} (máximo). Total: {d}/100. Sin compensación por información desconocida."
  ],
  [
   "{a} raw points",
   "{a} puntos brutos"
  ],
  [
   "raw weight {a}, family {b}",
   "peso bruto {a}, familia {b}"
  ],
  [
   "also known as {a}",
   "también conocido como {a}"
  ],
  [
   "If a link has moved, search the official portal for: {a}",
   "Si un enlace ha cambiado, busque en el portal oficial: {a}"
  ],
  [
   "How this row was collected: {a} See “Sources and how to verify” above the table.",
   "Cómo se obtuvo esta fila: {a} Vea «Fuentes y cómo verificar» encima de la tabla."
  ],
  [
   "Publisher: {a}. Licence: {b}.",
   "Editor: {a}. Licencia: {b}."
  ],
  [
   "What was collected: {a}",
   "Qué se recogió: {a}"
  ],
  [
   "Supplier document: {a}. A personal or tax identifier identifies the declared holder; it implies no suspicion and no link to other contracts by itself.",
   "Documento del proveedor: {a}. Un identificador personal o tributario identifica al titular declarado; por sí solo no implica sospecha ni vínculo con otros contratos."
  ],
  [
   "Declared modality: {a} · Contract status: {b} · Contract type: {c}.",
   "Modalidad declarada: {a} · Estado del contrato: {b} · Tipo de contrato: {c}."
  ],
  [
   "Buyer profile · {a}",
   "Perfil del comprador · {a}"
  ],
  [
   "Supplier profile · {a}",
   "Perfil del proveedor · {a}"
  ],
  [
   "{a} contract(s) · {b} · {c} → {d} · {e} assessed · {f} with a signal ({g}). The table below now shows only these contracts. Compared with the {h} records of the same dataset; amounts are never summed.",
   "{a} contrato(s) · {b} · {c} → {d} · {e} evaluados · {f} con señal ({g}). La tabla muestra ahora solo estos contratos. Comparado con los {h} registros del mismo conjunto; los montos nunca se suman."
  ],
  [
   "{a} contract(s) · {c} → {d} · {e} assessed · {f} with a signal ({g}). The table below now shows only these contracts. Compared with the {h} records of the same dataset; amounts are never summed.",
   "{a} contrato(s) · {c} → {d} · {e} evaluados · {f} con señal ({g}). La tabla muestra ahora solo estos contratos. Comparado con los {h} registros del mismo conjunto; los montos nunca se suman."
  ],
  [
   "{a} / {b} evaluated ({c})",
   "{a} / {b} evaluadas ({c})"
  ],
  [
   "{a} of {b} evaluated",
   "{a} de {b} evaluadas"
  ],
  [
   "{a} · {b} contract(s), {c} with a signal",
   "{a} · {b} contrato(s), {c} con señal"
  ],
  [
   "Declared amounts: {a}. Not summed: declared amounts are not payments, and ceilings and amendments would double count.",
   "Montos declarados: {a}. No se suman: los montos declarados no son pagos, y los topes y modificaciones se contarían dos veces."
  ],
  [
   "{a} day(s) added to a declared term of {b} months (+{c} %): not above +{d} %. Not a conclusion of regularity.",
   "{a} día(s) añadido(s) a un plazo declarado de {b} meses (+{c} %): no supera +{d} %. No es una conclusión de regularidad."
  ],
  [
   "Same buyer and contract type ({a}): {b}/{c} contracts to this holder, out of {d} in the group ({e} % coverage). Minimum {f} identified contracts and {g} % coverage; from {h} points at {i} % to {j} at {k} %. Specialisation may explain a share; computed over the whole cohort, before filters.",
   "Mismo comprador y tipo de contrato ({a}): {b}/{c} contratos a este titular, de {d} en el grupo ({e} % de cobertura). Mínimo {f} contratos identificados y {g} % de cobertura; de {h} puntos al {i} % a {j} al {k} %. La especialización puede explicar una cuota; calculado sobre toda la cohorte, antes de los filtros."
  ],
  [
   "Non-competitive modality ({a}) with the published justification “{b}”: an ordinary declared ground in this cohort, not a plurality/urgency claim. Threshold not crossed — not a conclusion of regularity.",
   "Modalidad no competitiva ({a}) con la justificación publicada «{b}»: un motivo ordinario declarado en esta cohorte, no una alegación de falta de pluralidad o urgencia. Umbral no superado — no es una conclusión de regularidad."
  ],
  [
   "{a} months declared. From {b} months: {c} points, linear progression up to {d} at {e} months; renewals are not invented. Not a sectoral comparison nor an illegality threshold.",
   "{a} meses declarados. Desde {b} meses: {c} puntos, progresión lineal hasta {d} a los {e} meses; no se inventan renovaciones. No es una comparación sectorial ni un umbral de ilegalidad."
  ],
  [
   "{a} months declared (parsed read-only from “{b}”): below the {c}-month entry threshold. Not a conclusion of regularity.",
   "{a} meses declarados (leídos sin modificar de «{b}»): por debajo del umbral de entrada de {c} meses. No es una conclusión de regularidad."
  ],
  [
   "{a} day(s) between the contract date ({b}) and the {c} ({d}): within {e} days. Not a conclusion of regularity.",
   "{a} día(s) entre la fecha del contrato ({b}) y {c} ({d}): dentro de {e} días. No es una conclusión de regularidad."
  ],
  [
   "{a} offer(s) declared, without presuming admissibility. One offer: {b} points, regardless of amount.",
   "{a} oferta(s) declarada(s), sin presumir su admisibilidad. Una oferta: {b} puntos, sea cual sea el monto."
  ],
  [
   "{a} offer(s) published for this lot ({b}). One offer: {c} points, all amounts. Admissibility is not assessed.",
   "{a} oferta(s) publicada(s) para este lote ({b}). Una oferta: {c} puntos, todos los montos. No se evalúa la admisibilidad."
  ],
  [
   "Competitive procedure ({a}): no direct-award signal.",
   "Procedimiento competitivo ({a}): sin señal de adjudicación directa."
  ],
  [
   "{a} days between the contract date ({b}) and the {c} ({d}). Above {e} days, beyond every legal deadline of the regimes covered: 8 points, linear to 16 at {f} days, in the transparency family. Late publication hides a contract from scrutiny while it runs; it can also be a clerical delay.",
   "{a} días entre la fecha del contrato ({b}) y {c} ({d}). Más de {e} días, por encima de todos los plazos legales de los regímenes cubiertos: 8 puntos, lineal hasta 16 a los {f} días, en la familia de transparencia. La publicación tardía oculta un contrato al escrutinio mientras se ejecuta; también puede ser un retraso administrativo."
  ],
  [
   "Publication date ({a}) before the contract date ({b}): inconsistent dates, not assessed.",
   "Fecha de publicación ({a}) anterior a la fecha del contrato ({b}): fechas incoherentes, no evaluado."
  ],
  [
   "{a} days, upper bound. Signal if < 15 days; 8 points near 15, 40 at 3 days or fewer. Editorial threshold, not a legal one.",
   "{a} días, cota superior. Señal si < 15 días; 8 puntos cerca de 15, 40 a 3 días o menos. Umbral editorial, no legal."
  ],
  [
   "Declared increase of {a} %. Signal strictly > 20 %, from 8 points near the threshold to 40 at +100 %. No euro threshold or bonus. Additional services possible: not a final expense nor a proven cost overrun.",
   "Aumento declarado del {a} %. Señal estrictamente > 20 %, de 8 puntos cerca del umbral a 40 con +100 %. Sin umbral en euros ni bonificación. Posibles prestaciones adicionales: no es un gasto final ni un sobrecoste probado."
  ],
  [
   "Same SIREN: {a}/{b} contracts to the known holder, out of {c} eligible; CPV {d}, 2024–2025. Minimum 10 and 80 % coverage. From 12 points at 60 % to 40 at 100 %. Specialisation and framework agreements may explain this share.",
   "Mismo SIREN: {a}/{b} contratos al titular conocido, de {c} elegibles; CPV {d}, 2024–2025. Mínimo 10 y 80 % de cobertura. De 12 puntos al 60 % a 40 al 100 %. La especialización y los acuerdos marco pueden explicar esta cuota."
  ],
  [
   "Same SIREN: {a}/{b} contracts to the known holder, out of {c} eligible; CPV {d}, 2024–2025. Minimum 10 and 80 % coverage. From 12 points at 60 % to 40 at 100 %. Specialisation and framework agreements may explain this share. Insufficient sample/coverage.",
   "Mismo SIREN: {a}/{b} contratos al titular conocido, de {c} elegibles; CPV {d}, 2024–2025. Mínimo 10 y 80 % de cobertura. De 12 puntos al 60 % a 40 al 100 %. La especialización y los acuerdos marco pueden explicar esta cuota. Muestra o cobertura insuficiente."
  ],
  [
   "{a} direct awards identified, all amounts, same buyer/CPV/SIREN, 2024–2025. From 18 points at 3 contracts to 60 at 10. Unknown procedures do not become competitive. Legal exceptions possible.",
   "{a} adjudicaciones directas identificadas, todos los montos, mismo comprador/CPV/SIREN, 2024–2025. De 18 puntos con 3 contratos a 60 con 10. Los procedimientos desconocidos no pasan a ser competitivos. Posibles excepciones legales."
  ],
  [
   "Maintenance, support or licences of an existing software product ({a}), placed with one vendor ({b}). This is often routine: only the publisher or its appointed distributor can maintain its product. Proprietary status and exclusive rights are not verified here. No points added or removed; the index is unchanged.",
   "Mantenimiento, soporte o licencias de un producto de software existente ({a}), contratado con un único proveedor ({b}). Suele ser rutinario: solo el editor o su distribuidor designado puede mantener su producto. El carácter propietario y los derechos exclusivos no se verifican aquí. No se suman ni restan puntos; el índice no cambia."
  ],
  [
   "Price form: {a} · Type: {b}. Declared amounts, not observed payments.",
   "Forma de precio: {a} · Tipo: {b}. Montos declarados, no pagos observados."
  ],
  [
   "Analysable declared evolution: +{a} (+{b} %), from {c} to {d}, on {e}. Quantities or scope may have changed; consult the source.",
   "Evolución declarada analizable: +{a} (+{b} %), de {c} a {d}, el {e}. Las cantidades o el alcance pueden haber cambiado; consulte la fuente."
  ],
  [
   "Increase calculation unavailable: {a}",
   "Cálculo del aumento no disponible: {a}"
  ],
  [
   "Single identified holder: SIREN {a}. Same buyer/CPV {b}, 2024–2025: {c}/{d} contracts to the known holder, out of {e} eligible contracts ({f} % coverage); {g} awards without competition identified to this holder, all amounts; {h}/{i} known competitive statuses. {j} The statistics do not change with your filters.",
   "Titular único identificado: SIREN {a}. Mismo comprador/CPV {b}, 2024–2025: {c}/{d} contratos al titular conocido, de {e} contratos elegibles ({f} % de cobertura); {g} adjudicaciones sin competencia identificadas a este titular, todos los montos; {h}/{i} estados competitivos conocidos. {j} Las estadísticas no cambian con sus filtros."
  ],
  [
   "Retrospective context {a}–{b}, same buyer and CPV {c}: {d} single-offer contracts / {e} with a known count, out of {f} eligible competitive contracts ({g} % coverage). {h} Computed over the whole cohort, unchanged by your filters.",
   "Contexto retrospectivo {a}–{b}, mismo comprador y CPV {c}: {d} contratos con una sola oferta / {e} con número conocido, de {f} contratos competitivos elegibles ({g} % de cobertura). {h} Calculado sobre toda la cohorte, sin cambios por sus filtros."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct procedure(s) in this cohort won with a single offer. From 12 points at 3, linear to 40 at 10.",
   "Mismo comprador y proveedor {a}: {b} procedimiento(s) distinto(s) de esta cohorte ganado(s) con una sola oferta. De 12 puntos con 3, lineal hasta 40 con 10."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct procedure(s) without competition in this cohort. From 18 points at 3, linear to 60 at 10. Lawful grounds may apply to each.",
   "Mismo comprador y proveedor {a}: {b} procedimiento(s) distinto(s) sin competencia en esta cohorte. De 18 puntos con 3, lineal hasta 60 con 10. Cada uno puede tener un motivo legal."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct process(es) in this cohort won as the only tenderer. From 12 points at {c}, linear to 40 at {d}. Computed over the whole cohort before filters.",
   "Mismo comprador y proveedor {a}: {b} proceso(s) distinto(s) de esta cohorte ganado(s) como único oferente. De 12 puntos con {c}, lineal hasta 40 con {d}. Calculado sobre toda la cohorte antes de los filtros."
  ],
  [
   "Same buyer and supplier {a}: {b} distinct process(es) awarded by exception in this cohort. From 18 points at {c}, linear to 60 at {d}. Lawful grounds may apply to each.",
   "Mismo comprador y proveedor {a}: {b} proceso(s) distinto(s) adjudicado(s) por excepción en esta cohorte. De 18 puntos con {c}, lineal hasta 60 con {d}. Cada uno puede tener un motivo legal."
  ],
  [
   "Same buyer and supplier document: {a} award(s) of this cohort declared without supplier plurality. From 18 points at {b} contracts, linear to 60 at {c}. Published declarations only; a lawful ground may still apply.",
   "Mismo comprador y documento del proveedor: {a} adjudicación(es) de esta cohorte declarada(s) sin pluralidad de oferentes. De 18 puntos con {b} contratos, lineal hasta 60 con {c}. Solo declaraciones publicadas; puede aplicarse un motivo legal."
  ],
  [
   "Same buyer and category {a}: {b}/{c} procedures won by this supplier, out of {d} ({e} % with an identified winner; lots of one procedure count once). Minimum 10 and 80 %; from 12 points at 60 % to 40 at 100 %. {f}",
   "Mismo comprador y categoría {a}: {b}/{c} procedimientos ganados por este proveedor, de {d} ({e} % con adjudicatario identificado; los lotes de un procedimiento cuentan una vez). Mínimo 10 y 80 %; de 12 puntos al 60 % a 40 al 100 %. {f}"
  ],
  [
   "Same buyer and category {a}: {b}/{c} procedures won by this supplier, out of {d} ({e} % with an identified winner; lots of one procedure count once). Minimum 10 and 80 %; from 12 points at 60 % to 40 at 100 %.",
   "Mismo comprador y categoría {a}: {b}/{c} procedimientos ganados por este proveedor, de {d} ({e} % con adjudicatario identificado; los lotes de un procedimiento cuentan una vez). Mínimo 10 y 80 %; de 12 puntos al 60 % a 40 al 100 %."
  ],
  [
   "{a} (OCDS procurementMethod limited): award without a competitive call. 18 points, all amounts. A lawful ground may apply (urgency, exclusivity, failed call); not assessed here.",
   "{a} (OCDS procurementMethod limited): adjudicación sin convocatoria competitiva. 18 puntos, todos los montos. Puede aplicarse un motivo legal (urgencia, exclusividad, convocatoria desierta); no se evalúa aquí."
  ],
  [
   "{a} ({b}): award without a competitive call. 18 points, all amounts. A lawful ground may apply (urgency, exclusivity, failed call); not assessed here.",
   "{a} ({b}): adjudicación sin convocatoria competitiva. 18 puntos, todos los montos. Puede aplicarse un motivo legal (urgencia, exclusividad, convocatoria desierta); no se evalúa aquí."
  ],
  [
   "{a} day(s) added to a declared term of {b} months (+{c} %). Strictly above +{d} %: 8 points, linear to 40 at +{e} %. Editorial threshold; an extension can be lawful and necessary (weather, design changes, budget calendars). Amount additions are not published in this extract.",
   "{a} día(s) añadido(s) a un plazo declarado de {b} meses (+{c} %). Estrictamente por encima de +{d} %: 8 puntos, lineal hasta 40 con +{e} %. Umbral editorial; una prórroga puede ser legal y necesaria (clima, cambios de diseño, calendario presupuestal). Las adiciones en valor no se publican en este extracto."
  ],
  [
   "{a} published amount amendment(s): +{b} % of the original declared amount. Signal strictly above 20 %, 8 points near the threshold to 40 at +100 %. Ley 7021/22 Art. 67 caps agreed modifications at 20 % of the original amount; DNCP rules allow a separate 20 % for unilateral public-interest changes (Art. 65 b), so a larger total is not by itself unlawful. Extra works or quantities may explain an increase; declared, not paid.",
   "{a} modificación(es) de monto publicada(s): +{b} % del monto original declarado. Señal estrictamente por encima del 20 %, de 8 puntos cerca del umbral a 40 con +100 %. La Ley 7021/22 Art. 67 limita las modificaciones acordadas al 20 % del monto original; las reglas de la DNCP permiten otro 20 % para cambios unilaterales de interés público (Art. 65 b), por lo que un total mayor no es ilegal por sí mismo. Obras o cantidades adicionales pueden explicar un aumento; declarado, no pagado."
  ],
  [
   "{a} better-ranked bidder(s) on this lot had their award declared unsuccessful before this award. 12 points, all amounts. Disqualification is often lawful (missing documents, non-compliant offer); read the award decisions linked on the Prozorro page.",
   "{a} oferente(s) mejor clasificado(s) en este lote vio/vieron su adjudicación declarada fallida antes de esta adjudicación. 12 puntos, todos los montos. La descalificación suele ser legal (documentos faltantes, oferta no conforme); lea las decisiones enlazadas en la página de Prozorro."
  ],
  [
   "Award without competition ({a})",
   "Adjudicación sin competencia ({a})"
  ],
  [
   "Direct modality “{a}” without a declared exception: ordinary direct contracting adds no points. Not a conclusion of regularity.",
   "Modalidad directa «{a}» sin excepción declarada: la contratación directa ordinaria no suma puntos. No es una conclusión de regularidad."
  ],
  [
   "Non-competitive modality ({a}) with the published justification “{b}”: the file itself declares an absent plurality of suppliers or manifest urgency. 18 points, all amounts. Ordinary grounds (professional services, interadministrative agreements, minimum-amount rules, regime statutes) add nothing; legality is not assessed here.",
   "Modalidad no competitiva ({a}) con la justificación publicada «{b}»: el propio expediente declara ausencia de pluralidad de oferentes o urgencia manifiesta. 18 puntos, todos los montos. Los motivos ordinarios (servicios profesionales, convenios interadministrativos, mínima cuantía, régimen especial) no suman; la legalidad no se evalúa aquí."
  ],
  [
   "{a} months declared (parsed read-only from “{b}”). From {c} months: 8 points, linear to 40 at {d} months. Editorial threshold for this cohort, not a Colombian legal threshold; renewals are not invented.",
   "{a} meses declarados (leídos sin modificar de «{b}»). Desde {c} meses: 8 puntos, lineal hasta 40 a los {d} meses. Umbral editorial para esta cohorte, no un umbral legal colombiano; no se inventan renovaciones."
  ],
  [
   "Date: {a}",
   "Fecha: {a}"
  ],
  [
   "{a} — editorial index, not a probability nor legal gravity.",
   "{a} — índice editorial, no una probabilidad ni una gravedad jurídica."
  ],
  [
   "{a} of {b} applicable checks evaluated.",
   "{a} de {b} controles aplicables evaluados."
  ],
  [
   "{a} with unknown applicability.",
   "{a} de aplicabilidad desconocida."
  ],
  [
   "All {a} checks",
   "Los {a} controles"
  ],
  [
   "Amendments ({a})",
   "Modificaciones ({a})"
  ],
  [
   "Change {a}",
   "Modificación {a}"
  ],
  [
   "Amendments reach the legal 20 % ceiling (+{a} %).",
   "Las modificaciones alcanzan el tope legal del 20 % (+{a} %)."
  ],
  [
   "{a} complaint(s) filed on this tender.",
   "{a} reclamación(es) presentada(s) sobre esta licitación."
  ],
  [
   "Joint purchase: {a}",
   "Compra conjunta: {a}"
  ],
  [
   "Legal basis: {a}",
   "Base jurídica: {a}"
  ],
  [
   "Bidding period not assessable: {a}",
   "Plazo de presentación no evaluable: {a}"
  ],
  [
   "Bidding period: {a} days (upper bound).",
   "Plazo de presentación: {a} días (límite superior)."
  ],
  [
   "Conflicting initial versions ({a}): no chronology inferred.",
   "Versiones iniciales contradictorias ({a}): no se infiere ninguna cronología."
  ],
  [
   "Official audit finding: {a}.",
   "Hallazgo oficial de auditoría: {a}."
  ],
  [
   "Colour theme: {a} · click to change",
   "Tema de color: {a} · clic para cambiar"
  ],
  [
   "Colour theme: {a}. Change theme.",
   "Tema de color: {a}. Cambiar tema."
  ],
  [
   "Also known as {a}",
   "También conocido como {a}"
  ]
 ]
};
