// npm install --prefix /tmp/procurement-browser playwright (test-only, never a site dependency)
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/tmp/procurement-browser/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 await page.selectOption('#assessment','unevaluated');
 assert.match(await page.locator('#status').textContent(),/355 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/1835 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/0 \/ 100/);
 await page.locator('.row-toggle').first().click();
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/unknown applicabilities/);
 await page.selectOption('#assessment','');
 await page.selectOption('#legal','R2122-1');
 assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row').textContent(),/R-2122-1/);
 assert.match(await page.locator('.detail-row').textContent(),/No points added/);
 await page.selectOption('#legal','R2122-3');assert.equal(await page.locator('.contract-row').count(),4);
 await page.selectOption('#legal','');
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const before=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 await page.click('#next');
 assert.match(await page.locator('#page-status').textContent(),/Page 2/);
 const after=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 assert.deepEqual(after,before);
 await page.selectOption('#group-by','buyer');await page.selectOption('#sort','date-asc');
 assert(await page.locator('.group-row').count()>0);
 await page.selectOption('#dataset','cities');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 assert.match(await page.locator('#dataset-note').textContent(),/172 ambiguous/);
 await page.selectOption('#group-by','buyer');
 assert(await page.locator('.group-row').count()>0);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const cityPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');
 assert.equal(await page.evaluate(()=>scrollY),cityPosition);
 const cityData=require('../data/decp-cities.json');
 const profile=cityData.find(c=>c.supplierProfiles?.length).supplierProfiles[0];
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/Current public identity — not historical/);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/SIREN/);
 await page.selectOption('#dataset','tours');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const toursPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');assert.equal(await page.evaluate(()=>scrollY),toursPosition);
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','correction');assert.equal(await page.locator('.contract-row').count(),6);
 await page.fill('#search','25-127301');
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/40/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/per-exa/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/25-119055/);
 assert(await page.locator('.detail-row:not([hidden]) a[download]').count()>0);
 await page.selectOption('#notice-context','');await page.fill('#search','R2122-8');
 assert.equal(await page.locator('.contract-row').count(),3);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/lots other than/);
 await page.selectOption('#dataset','consultations');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.fill('#search','25-22678');assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();assert.match(await page.locator('.detail-row').textContent(),/14 mars 2025/);
 assert.match(await page.locator('.detail-row').textContent(),/not assessable/);
 await page.selectOption('#indicator','short-bidding-period');assert.equal(await page.locator('.contract-row').count(),0);
 // Colombia SECOP II pilot: jurisdiction-specific indicators, Spanish source text, COP amounts
 await page.selectOption('#dataset','colombia');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 7560'));
 assert.match(await page.locator('#dataset-note').textContent(),/SECOP II pilot · Colombia/);
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('#status').textContent(),/215 with a heuristic signal/);
 assert.match(await page.locator('#status').textContent(),/0 not assessed/);
 await page.check('#flagged');
 assert.match(await page.locator('#status').textContent(),/215 \/ 7560/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Award declared without supplier plurality|Repeated awards declared without supplier plurality|Long declared duration/);
 await page.uncheck('#flagged');
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/7345 \/ 7560/);
 await page.selectOption('#assessment','');
 await page.selectOption('#indicator','secop2-plurality-award');
 assert.match(await page.locator('#status').textContent(),/176 \/ 7560/);
 await page.selectOption('#indicator','');
 await page.fill('#search','GOBERNACION DE CALDAS');
 assert.match(await page.locator('#status').textContent(),/3696 \/ 7560/);
 await page.fill('#search','');
 await page.locator('.row-toggle').first().click();
 const copDetail=await page.locator('.detail-row:not([hidden])').first().textContent();
 assert.match(copDetail,/Declared modality/);
 assert.match(copDetail,/SECOP II — detalle del proceso/);
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(copDetail,/docs\/score-colombia\.md|Colombian check/);
 await page.selectOption('#dataset','decp');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 await page.goto('file://'+path.resolve('index.html'));
 await page.waitForSelector('#file-help',{state:'visible'});
 await page.setInputFiles('#file',path.resolve('data/consultations.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.setInputFiles('#file',path.resolve('data/tours-notices.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','');
 await page.setInputFiles('#file',path.resolve('data/decp-cities.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.fill('#search','');
 await page.setInputFiles('#file',path.resolve('data/contracts.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 3010'));
 await page.check('#official');assert.equal(await page.locator('.contract-row').count(),8);
 assert.equal(await page.locator('.contract-row .badge.official').count(),8);
 assert.match(await page.locator('.contract-row').first().textContent(),/outside the index/);
 await page.uncheck('#official');await page.selectOption('#sort','official');
 for(let i=0;i<8;i++)assert.match(await page.locator('.contract-row').nth(i).textContent(),/Official finding · outside the index/);
 assert(!((await page.locator('body').textContent()).includes('null / 100')));
 assert.deepEqual(errors,[]);
 await browser.close();console.log('HTTP, file:// picker (including city profiles), legal/correction/identity panels, filters, sorting, grouping and stationary pagination: passed.');
})().catch(e=>{console.error(e);process.exit(1)});
