// npm install --prefix /tmp/procurement-browser playwright (test-only, never a site dependency)
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/tmp/procurement-browser/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const http = require('node:http');
const fs = require('node:fs');
// Own static server on a free port (or PORT): no collision with other local servers.
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.md':'text/markdown; charset=utf-8','.xml':'application/xml','.pdf':'application/pdf'};
const server=http.createServer((req,res)=>{
 const file=path.join(process.cwd(),decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/\/$/,'/index.html'));
 if(!file.startsWith(process.cwd())||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}
 res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);
});
(async()=>{
 await new Promise(resolve=>server.listen(Number(process.env.PORT)||0,'127.0.0.1',resolve));
 const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 assert.match(await page.locator('#dataset option:checked').textContent(),/France.*Paris.*contracts.*DECP/);
 await page.selectOption('#page-size','100');
 assert.equal(await page.locator('.contract-row').count(),100);
 assert.match(await page.locator('#page-status').textContent(),/100 rows per page/);
 await page.selectOption('#page-size','50');
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.equal(await page.locator('#advanced-filters').getAttribute('open'),null);
 await page.locator('#advanced-filters summary').click();
 await page.selectOption('#assessment','unevaluated');
 assert.match(await page.locator('#advanced-count').textContent(),/1 active/);
 await page.locator('#advanced-filters summary').click();
 assert.equal(await page.locator('#advanced-filters').getAttribute('open'),null);
 assert.match(await page.locator('#advanced-count').textContent(),/1 active/);
 await page.locator('#advanced-filters summary').click();
 await page.click('#clear-filters');
 assert.match(await page.locator('#status').textContent(),/2594 \/ 2594/);
 await page.selectOption('#assessment','unevaluated');
 assert.match(await page.locator('#status').textContent(),/355 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/1835 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/0 \/ 100/);
 await page.locator('.row-toggle').first().click();
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/unknown applicabilities/);
 await page.selectOption('#assessment','');
 await page.selectOption('#legal','R2122-1');
 assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row').textContent(),/R-2122-1/);
 assert.match(await page.locator('.detail-row').textContent(),/No points added/);
 await page.selectOption('#legal','R2122-3');assert.equal(await page.locator('.contract-row').count(),4);
 await page.selectOption('#legal','');
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const before=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 await page.click('#next');
 assert.match(await page.locator('#page-status').textContent(),/Page 2/);
 const after=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 assert.deepEqual(after,before);
 await page.selectOption('#group-by','buyer');await page.selectOption('#sort','date-asc');
 assert(await page.locator('.group-row').count()>0);
 await page.selectOption('#dataset','cities');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 assert.match(await page.locator('#dataset-note').textContent(),/172 ambiguous/);
 await page.selectOption('#group-by','buyer');
 assert(await page.locator('.group-row').count()>0);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const cityPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');
 assert.equal(await page.evaluate(()=>scrollY),cityPosition);
 const cityData=require('../data/decp-cities.json');
 const profile=cityData.find(c=>c.supplierProfiles?.length).supplierProfiles[0];
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/Current public identity — not historical/);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/SIREN/);
 await page.selectOption('#dataset','tours');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const toursPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');assert.equal(await page.evaluate(()=>scrollY),toursPosition);
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','correction');assert.equal(await page.locator('.contract-row').count(),6);
 await page.fill('#search','25-127301');
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/40/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/per-exa/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/25-119055/);
 assert(await page.locator('.detail-row:not([hidden]) a[download]').count()>0);
 await page.selectOption('#notice-context','');await page.fill('#search','R2122-8');
 assert.equal(await page.locator('.contract-row').count(),3);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/lots other than/);
 await page.selectOption('#dataset','consultations');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.fill('#search','25-22678');assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();assert.match(await page.locator('.detail-row').textContent(),/14 mars 2025/);
 assert.match(await page.locator('.detail-row').textContent(),/not assessable/);
 await page.selectOption('#indicator','short-bidding-period');assert.equal(await page.locator('.contract-row').count(),0);
 // Colombia SECOP II pilot: jurisdiction-specific indicators, Spanish source text, COP amounts
 await page.selectOption('#dataset','colombia');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 7560'));
 await page.check('#adjudicated');
 assert.match(await page.locator('#status').textContent(),/0 \/ 7560/);
 await page.uncheck('#adjudicated');
 assert.match(await page.locator('#dataset-note').textContent(),/SECOP II pilot · Colombia/);
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('#status').textContent(),/215 with a heuristic signal/);
 assert.match(await page.locator('#status').textContent(),/0 not assessed/);
 await page.check('#flagged');
 assert.match(await page.locator('#status').textContent(),/215 \/ 7560/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Award declared without supplier plurality|Repeated awards declared without supplier plurality|Long declared duration/);
 await page.uncheck('#flagged');
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/7345 \/ 7560/);
 await page.selectOption('#assessment','');
 await page.selectOption('#indicator','secop2-plurality-award');
 assert.match(await page.locator('#status').textContent(),/176 \/ 7560/);
 await page.selectOption('#indicator','');
 await page.fill('#search','GOBERNACION DE CALDAS');
 assert.match(await page.locator('#status').textContent(),/3696 \/ 7560/);
 await page.fill('#search','');
 await page.locator('.row-toggle').first().click();
 const copDetail=await page.locator('.detail-row:not([hidden])').first().textContent();
 assert.match(copDetail,/Declared modality/);
 assert.match(copDetail,/SECOP II — detalle del proceso/);
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(copDetail,/docs\/score-colombia\.md|Colombian check/);
 // Paraguay: linked contract records scored with Paraguayan checks only (docs/score-paraguay.md).
 await page.selectOption('#dataset','paraguay');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 84'));
 assert.match(await page.locator('#dataset-note').textContent(),/Fernando de la Mora/);
 assert.match(await page.locator('#dataset option:checked').textContent(),/Paraguay.*Fernando de la Mora.*contract records.*DNCP OCDS/);
 assert.match(await page.locator('#status').textContent(),/35 with a heuristic signal · 0 not assessed/);
 assert.equal(await page.locator('#dataset-sources').isHidden(),false);
 const pySources=await page.locator('#sources-body').textContent();
 assert.match(pySources,/Dirección Nacional de Contrataciones Públicas/);
 assert.match(pySources,/CC BY 4\.0/);
 assert.match(pySources,/data\/paraguay-dncp\/raw\//);
 assert.match(pySources,/import-paraguay-dncp\.py --cohort fernando --offline/);
 await page.selectOption('#page-size','250');
 assert.equal(await page.locator('.contract-row').count(),84);
 assert.equal(await page.locator('#pagination').isVisible(),true);
 await page.selectOption('#page-size','50');
 await page.click('#copy-page');
 await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.includes('copied'));
 const copied=await page.evaluate(()=>navigator.clipboard.readText());
 assert.match(copied,/Paraguay.*Fernando de la Mora.*DNCP OCDS/);
 assert.match(copied,/Page 1 \/ 2 · 50 of 84 filtered records/);
 assert.match(copied,/Record source: https:\/\/www\.contrataciones\.gov\.py\/datos\/api\/v3\/doc\/ocds\/record\//);
 assert.equal((copied.match(/^\[\d+\] /gm)||[]).length,50);
 await page.check('#adjudicated');
 assert.equal(await page.locator('#copy-page').isDisabled(),true);
 assert.match(await page.locator('#status').textContent(),/0 \/ 84/);
 await page.uncheck('#adjudicated');
 assert.doesNotMatch(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.locator('.row-toggle').first().click();
 const pyDetail=await page.locator('.detail-row:not([hidden])').first().textContent();
 assert.match(pyDetail,/Contract period starts/);
 assert.match(pyDetail,/Signature date: not published/);
 assert.match(pyDetail,/PYG/);
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(pyDetail,/Verify it yourself/);
 assert.match(pyDetail,/Award page on contrataciones\.gov\.py/);
 assert.match(pyDetail,/search the official portal for: OCID ocds-/);
 assert.match(await page.locator('.detail-row:not([hidden]) .verify a').first().getAttribute('href'),/^https:\/\/www\.contrataciones\.gov\.py\/licitaciones\/adjudicacion\//);
 assert.match(copied,/Verify: Award page on contrataciones\.gov\.py/);
 await page.selectOption('#dataset','paraguay3');
 await page.waitForFunction(()=>/\/ \d+ results/.test(document.querySelector('#status').textContent)&&document.querySelector('#dataset-note').textContent.includes('Asunción'));
 assert.match(await page.locator('#dataset option:checked').textContent(),/Paraguay.*MOPC.*Central.*Asunción/);
 assert.match(await page.locator('#sources-body').textContent(),/--cohort 3buyers --offline/);
 await page.selectOption('#dataset','decp');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 // Shareable links: a fresh load restores dataset, filters, sort, page and page size.
 const linked=await browser.newPage({viewport:{width:1280,height:900}});
 linked.on('pageerror',e=>errors.push(e.message));
 await linked.goto(base+'/#dataset=cities&sort=amount&flagged=1&page=2&size=25');
 await linked.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 assert.equal(await linked.locator('#dataset').inputValue(),'cities');
 assert.equal(await linked.locator('#sort').inputValue(),'amount');
 assert.equal(await linked.locator('#flagged').isChecked(),true);
 assert.match(await linked.locator('#page-status').textContent(),/Page 2 \/ \d+ · 25 rows per page/);
 assert.equal(await linked.locator('.contract-row').count(),25);
 assert.equal(await linked.evaluate(()=>location.hash),'#dataset=cities&sort=amount&flagged=1&page=2&size=25');
 // A restored sort shows on its column header; clicking headers drives the same Sort control and link.
 assert.equal(await linked.locator('th[data-sort-key="amount"]').getAttribute('aria-sort'),'descending');
 await linked.locator('th[data-sort-key="amount"] button').click();
 assert.equal(await linked.locator('#sort').inputValue(),'amount-asc');
 assert.equal(await linked.locator('th[data-sort-key="amount"]').getAttribute('aria-sort'),'ascending');
 assert.match(await linked.evaluate(()=>location.hash),/sort=amount-asc/);
 await linked.locator('th[data-sort-key="indicators"] button').click();
 assert.equal(await linked.locator('#sort').inputValue(),'indicators');
 assert.equal(await linked.locator('th[data-sort-key="amount"]').getAttribute('aria-sort'),'none');
 await linked.locator('th[data-sort-key="score"] button').click();
 assert.equal(await linked.locator('#sort').inputValue(),'score');
 await linked.selectOption('#sort','amount');
 await linked.selectOption('#sort','date');
 assert.equal(await linked.evaluate(()=>location.hash),'#dataset=cities&sort=date&flagged=1&size=25');
 // Export covers every filtered record, not only the visible page.
 const flaggedTotal=Number((await linked.locator('#status').textContent()).split(' / ')[0]);
 const [csvDownload]=await Promise.all([linked.waitForEvent('download'),linked.click('#export-csv')]);
 assert.match(csvDownload.suggestedFilename(),/^contract-signals-cities-\d{4}-\d{2}-\d{2}\.csv$/);
 const csv=fs.readFileSync(await csvDownload.path(),'utf8');
 assert.ok(csv.startsWith('\ufeffid,date,buyer,'));
 assert.equal(csv.split('\r\n').filter(line=>line.startsWith('decp-')).length,flaggedTotal);
 const [jsonDownload]=await Promise.all([linked.waitForEvent('download'),linked.click('#export-json')]);
 const exported=JSON.parse(fs.readFileSync(await jsonDownload.path(),'utf8'));
 assert.equal(exported.count,flaggedTotal);assert.equal(exported.view,'#dataset=cities&sort=date&flagged=1&size=25');
 // A pasted link on an open page switches dataset through hashchange; names are shown before identifiers.
 await linked.evaluate(siren=>{location.hash='#dataset=decp&q='+siren;},profile.siren);
 await linked.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 await linked.evaluate(siren=>{location.hash='#dataset=cities&q='+siren;},profile.siren);
 await linked.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 assert.equal(await linked.locator('#search').inputValue(),profile.siren);
 const supplierCell=await linked.locator('.contract-row td:nth-child(3)').first().textContent();
 assert.ok(supplierCell.startsWith(profile.name),supplierCell);
 assert.match(supplierCell,/SIRET \d{14} · current name \(\d{4}-\d{2}-\d{2}\), not historical/);
 await linked.close();
 await page.goto('file://'+path.resolve('index.html'));
 await page.waitForSelector('#file-help',{state:'visible'});
 await page.locator('#advanced-filters summary').click();
 await page.setInputFiles('#file',path.resolve('data/consultations.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.setInputFiles('#file',path.resolve('data/tours-notices.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','');
 await page.setInputFiles('#file',path.resolve('data/decp-cities.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.fill('#search','');
 await page.setInputFiles('#file',path.resolve('data/contracts.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 3010'));
 await page.check('#investigation');
 assert.equal(await page.locator('.contract-row').count(),1);
 assert.match(await page.locator('.contract-row').textContent(),/Station Nuage/);
 assert.match(await page.locator('.contract-row').textContent(),/current status unknown/);
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/Presse Océan.*2024-09-11/);
 await page.uncheck('#investigation');
 await page.check('#official');assert.equal(await page.locator('.contract-row').count(),8);
 assert.equal(await page.locator('.contract-row .provenance').filter({hasText:'Official audit finding'}).count(),8);
 assert.match(await page.locator('.contract-row').first().textContent(),/not a conviction/);
 await page.uncheck('#official');await page.selectOption('#sort','official');
 for(let i=0;i<8;i++)assert.match(await page.locator('.contract-row').nth(i).textContent(),/Official audit finding/);
 assert(!((await page.locator('body').textContent()).includes('null / 100')));
 assert.deepEqual(errors,[]);
 const mobile=await browser.newPage({viewport:{width:390,height:844}});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto(base);
 await mobile.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 assert.equal(await mobile.locator('#advanced-filters').getAttribute('open'),null);
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await mobile.locator('.contract-row').first().locator('td:visible').count(),3);
 // Paraguayan rows carry a note under the date; it must wrap, not squeeze the subject.
 const pyMobile=await browser.newPage({viewport:{width:390,height:844}});
 pyMobile.on('pageerror',e=>errors.push(e.message));
 await pyMobile.goto(base+'/#dataset=paraguay3');
 await pyMobile.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 293'));
 const pyCells=await pyMobile.locator('.contract-row').first().evaluate(r=>[...r.children].filter(td=>getComputedStyle(td).display!=='none').map(td=>({w:td.getBoundingClientRect().width,over:td.scrollWidth-td.clientWidth})));
 assert.ok(pyCells[1].w>=150,`subject column too narrow on mobile: ${pyCells[1].w}px`);
 assert.ok(pyCells.every(c=>c.over<=0),'a mobile cell overflows');
 // Opening a row must not squeeze the subject: full-width rows span only the visible columns.
 await pyMobile.locator('.row-toggle').first().click();
 const openWidth=await pyMobile.locator('.contract-row').first().evaluate(r=>[...r.children].filter(td=>getComputedStyle(td).display!=='none')[1].getBoundingClientRect().width);
 assert.ok(openWidth>=150,`subject column squeezed after opening a row: ${openWidth}px`);
 assert.equal(await pyMobile.locator('.detail-row:not([hidden]) td').getAttribute('colspan'),'3');
 await pyMobile.close();
 await mobile.locator('.row-toggle').first().click();
 assert.equal(await mobile.locator('.detail-row:not([hidden])').count(),1);
 await mobile.locator('#advanced-filters summary').click();
 await mobile.selectOption('#group-by','buyer');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.click('#clear-filters');
 assert.equal(await mobile.locator('#advanced-count').textContent(),'');
 assert.deepEqual(errors,[]);
 await mobile.close();
 await browser.close();server.close();console.log('HTTP, file:// picker, compact/advanced filters, mobile rows and evidence panels: passed.');
})().catch(e=>{console.error(e);server.close();process.exit(1)});
