// npm install --prefix /tmp/procurement-browser playwright (test-only, never a site dependency)
const { chromium } = require(process.env.PLAYWRIGHT_PATH || '/tmp/procurement-browser/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:900}});
 await page.context().grantPermissions(['clipboard-read','clipboard-write']);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 assert.match(await page.locator('#dataset option:checked').textContent(),/France.*Paris.*contracts.*DECP/);
 await page.selectOption('#page-size','100');
 assert.equal(await page.locator('.contract-row').count(),100);
 assert.match(await page.locator('#page-status').textContent(),/100 rows per page/);
 await page.selectOption('#page-size','50');
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.equal(await page.locator('#advanced-filters').getAttribute('open'),null);
 await page.locator('#advanced-filters summary').click();
 await page.selectOption('#assessment','unevaluated');
 assert.match(await page.locator('#advanced-count').textContent(),/1 active/);
 await page.locator('#advanced-filters summary').click();
 assert.equal(await page.locator('#advanced-filters').getAttribute('open'),null);
 assert.match(await page.locator('#advanced-count').textContent(),/1 active/);
 await page.locator('#advanced-filters summary').click();
 await page.click('#clear-filters');
 assert.match(await page.locator('#status').textContent(),/2594 \/ 2594/);
 await page.selectOption('#assessment','unevaluated');
 assert.match(await page.locator('#status').textContent(),/355 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/1835 \/ 2594/);
 assert.match(await page.locator('.contract-row').first().textContent(),/0 \/ 100/);
 await page.locator('.row-toggle').first().click();
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/unknown applicabilities/);
 await page.selectOption('#assessment','');
 await page.selectOption('#legal','R2122-1');
 assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row').textContent(),/R-2122-1/);
 assert.match(await page.locator('.detail-row').textContent(),/No points added/);
 await page.selectOption('#legal','R2122-3');assert.equal(await page.locator('.contract-row').count(),4);
 await page.selectOption('#legal','');
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const before=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 await page.click('#next');
 assert.match(await page.locator('#page-status').textContent(),/Page 2/);
 const after=await page.evaluate(()=>({y:scrollY,height:document.querySelector('.table-wrap').clientHeight}));
 assert.deepEqual(after,before);
 await page.selectOption('#group-by','buyer');await page.selectOption('#sort','date-asc');
 assert(await page.locator('.group-row').count()>0);
 await page.selectOption('#dataset','cities');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 assert.match(await page.locator('#dataset-note').textContent(),/172 ambiguous/);
 await page.selectOption('#group-by','buyer');
 assert(await page.locator('.group-row').count()>0);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const cityPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');
 assert.equal(await page.evaluate(()=>scrollY),cityPosition);
 const cityData=require('../data/decp-cities.json');
 const profile=cityData.find(c=>c.supplierProfiles?.length).supplierProfiles[0];
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/Current public identity — not historical/);
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/SIREN/);
 await page.selectOption('#dataset','tours');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.locator('#pagination').scrollIntoViewIfNeeded();
 const toursPosition=await page.evaluate(()=>scrollY);
 await page.click('#next');assert.equal(await page.evaluate(()=>scrollY),toursPosition);
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','correction');assert.equal(await page.locator('.contract-row').count(),6);
 await page.fill('#search','25-127301');
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/40/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/per-exa/);
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/25-119055/);
 assert(await page.locator('.detail-row:not([hidden]) a[download]').count()>0);
 await page.selectOption('#notice-context','');await page.fill('#search','R2122-8');
 assert.equal(await page.locator('.contract-row').count(),3);
 await page.locator('.row-toggle').first().click();
 assert.match(await page.locator('.detail-row:not([hidden])').first().textContent(),/lots other than/);
 await page.selectOption('#dataset','consultations');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.fill('#search','25-22678');assert.equal(await page.locator('.contract-row').count(),1);
 await page.locator('.row-toggle').click();assert.match(await page.locator('.detail-row').textContent(),/14 mars 2025/);
 assert.match(await page.locator('.detail-row').textContent(),/not assessable/);
 await page.selectOption('#indicator','short-bidding-period');assert.equal(await page.locator('.contract-row').count(),0);
 // Colombia SECOP II pilot: jurisdiction-specific indicators, Spanish source text, COP amounts
 await page.selectOption('#dataset','colombia');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 7560'));
 await page.check('#adjudicated');
 assert.match(await page.locator('#status').textContent(),/0 \/ 7560/);
 await page.uncheck('#adjudicated');
 assert.match(await page.locator('#dataset-note').textContent(),/SECOP II pilot · Colombia/);
 assert.equal(await page.locator('.contract-row').count(),50);
 assert.match(await page.locator('#status').textContent(),/215 with a heuristic signal/);
 assert.match(await page.locator('#status').textContent(),/0 not assessed/);
 await page.check('#flagged');
 assert.match(await page.locator('#status').textContent(),/215 \/ 7560/);
 assert.match(await page.locator('.contract-row').first().textContent(),/Award declared without supplier plurality|Repeated awards declared without supplier plurality|Long declared duration/);
 await page.uncheck('#flagged');
 await page.selectOption('#assessment','zero');
 assert.match(await page.locator('#status').textContent(),/7345 \/ 7560/);
 await page.selectOption('#assessment','');
 await page.selectOption('#indicator','secop2-plurality-award');
 assert.match(await page.locator('#status').textContent(),/176 \/ 7560/);
 await page.selectOption('#indicator','');
 await page.fill('#search','GOBERNACION DE CALDAS');
 assert.match(await page.locator('#status').textContent(),/3696 \/ 7560/);
 await page.fill('#search','');
 await page.locator('.row-toggle').first().click();
 const copDetail=await page.locator('.detail-row:not([hidden])').first().textContent();
 assert.match(copDetail,/Declared modality/);
 assert.match(copDetail,/SECOP II — detalle del proceso/);
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),8);
 assert.match(copDetail,/docs\/score-colombia\.md|Colombian check/);
 // Paraguay: records are linked contracts, but no local scoring method is approved.
 await page.selectOption('#dataset','paraguay');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 84'));
 assert.match(await page.locator('#dataset-note').textContent(),/Fernando de la Mora/);
 assert.match(await page.locator('#dataset option:checked').textContent(),/Paraguay.*Fernando de la Mora.*contract records.*DNCP OCDS/);
 assert.match(await page.locator('#status').textContent(),/84 not assessed/);
 await page.selectOption('#page-size','250');
 assert.equal(await page.locator('.contract-row').count(),84);
 assert.equal(await page.locator('#pagination').isVisible(),true);
 await page.selectOption('#page-size','50');
 await page.click('#copy-page');
 await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.includes('copied'));
 const copied=await page.evaluate(()=>navigator.clipboard.readText());
 assert.match(copied,/Paraguay.*Fernando de la Mora.*DNCP OCDS/);
 assert.match(copied,/Page 1 \/ 2 · 50 of 84 filtered records/);
 assert.match(copied,/Record source: https:\/\/www\.contrataciones\.gov\.py\/datos\/api\/v3\/doc\/ocds\/record\//);
 assert.equal((copied.match(/^\[\d+\] /gm)||[]).length,50);
 await page.check('#adjudicated');
 assert.equal(await page.locator('#copy-page').isDisabled(),true);
 assert.match(await page.locator('#status').textContent(),/0 \/ 84/);
 await page.uncheck('#adjudicated');
 assert.match(await page.locator('.contract-row').first().textContent(),/Not assessed/);
 await page.locator('.row-toggle').first().click();
 const pyDetail=await page.locator('.detail-row:not([hidden])').first().textContent();
 assert.match(pyDetail,/Contract period starts/);
 assert.match(pyDetail,/Signature date: not published/);
 assert.match(pyDetail,/PYG/);
 assert.equal(await page.locator('.detail-row:not([hidden]) .assessment-checks li').count(),1);
 await page.selectOption('#dataset','decp');
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 await page.goto('file://'+path.resolve('index.html'));
 await page.waitForSelector('#file-help',{state:'visible'});
 await page.locator('#advanced-filters summary').click();
 await page.setInputFiles('#file',path.resolve('data/consultations.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 10'));
 assert.equal(await page.locator('.contract-row').count(),10);
 await page.setInputFiles('#file',path.resolve('data/tours-notices.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 66'));
 await page.selectOption('#notice-context','criteria');assert.equal(await page.locator('.contract-row').count(),25);
 await page.selectOption('#notice-context','');
 await page.setInputFiles('#file',path.resolve('data/decp-cities.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 1270'));
 await page.fill('#search',profile.name);
 assert(await page.locator('.contract-row').count()>0);
 await page.fill('#search','');
 await page.setInputFiles('#file',path.resolve('data/contracts.json'));
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 3010'));
 await page.check('#investigation');
 assert.equal(await page.locator('.contract-row').count(),1);
 assert.match(await page.locator('.contract-row').textContent(),/Station Nuage/);
 assert.match(await page.locator('.contract-row').textContent(),/current status unknown/);
 await page.locator('.row-toggle').click();
 assert.match(await page.locator('.detail-row:not([hidden])').textContent(),/Presse Océan.*2024-09-11/);
 await page.uncheck('#investigation');
 await page.check('#official');assert.equal(await page.locator('.contract-row').count(),8);
 assert.equal(await page.locator('.contract-row .provenance').filter({hasText:'Official audit finding'}).count(),8);
 assert.match(await page.locator('.contract-row').first().textContent(),/not a conviction/);
 await page.uncheck('#official');await page.selectOption('#sort','official');
 for(let i=0;i<8;i++)assert.match(await page.locator('.contract-row').nth(i).textContent(),/Official audit finding/);
 assert(!((await page.locator('body').textContent()).includes('null / 100')));
 assert.deepEqual(errors,[]);
 const mobile=await browser.newPage({viewport:{width:390,height:844}});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://127.0.0.1:8765');
 await mobile.waitForFunction(()=>document.querySelector('#status').textContent.includes('/ 2594'));
 assert.equal(await mobile.locator('#advanced-filters').getAttribute('open'),null);
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await mobile.locator('.contract-row').first().locator('td:visible').count(),3);
 await mobile.locator('.row-toggle').first().click();
 assert.equal(await mobile.locator('.detail-row:not([hidden])').count(),1);
 await mobile.locator('#advanced-filters summary').click();
 await mobile.selectOption('#group-by','buyer');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await mobile.click('#clear-filters');
 assert.equal(await mobile.locator('#advanced-count').textContent(),'');
 assert.deepEqual(errors,[]);
 await mobile.close();
 await browser.close();console.log('HTTP, file:// picker, compact/advanced filters, mobile rows and evidence panels: passed.');
})().catch(e=>{console.error(e);process.exit(1)});
