'use strict';
const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const importer = require('../import.js');
const ctx = vm.createContext({ URL, URLSearchParams });
vm.runInContext(fs.readFileSync('script.js', 'utf8'), ctx);
const run = (fn, ...args) => { ctx.args = args; return vm.runInContext(`${fn}(...args)`, ctx); };
const text = JSON.stringify([{ id: 'local', buyer: 'Buyer', description: 'Work', amount: 42, offers: 1, directAward: true, durationMonths: 150, dataStatus: 'verified', dataFamily: 'secop2' }]);
const browsed = run('prepareContracts', importer.parse(text).records)[0];
assert.equal(run('getVigilanceScore', browsed), null);
assert.equal(run('getIndicators', browsed).length, 0);
const evidenceIds = ['cap', 'execution', 'legalGround', 'unitPrice', 'exclusivity'];
assert.ok(run('getAssessment', browsed).checks.every(c => !evidenceIds.includes(c.id)));
assert.equal(run('exportRecord', browsed).currency, null);
assert.match(run('pageSummaryForCopy', [browsed], { dataset: 'Local', page: 1, totalPages: 1, totalResults: 1 }), /currency unknown/);
const french = run('prepareContracts', importer.parse(text, { method: 'french' }).records)[0];
assert.ok(run('getVigilanceScore', french) > 0);
assert.equal(french.supplierContext, null);
assert.equal(french.competitionContext, null);
const unverified = run('prepareContracts', importer.parse('id,buyer,description,offers,directAward\nx,B,D,1,true', { method: 'french' }).records)[0];
assert.equal(run('getVigilanceScore', unverified), null);
assert.equal(run('csvCell', '  =HYPERLINK("x")').startsWith('"\''), true);
assert.equal(run('csvCell', '\n@SUM(A1)').startsWith('"\''), true);
assert.throws(() => run('prepareContracts', importer.parse('id,buyer,description\nx,b,d\nx,b,d').records), /unique text identifier/);
assert.throws(() => run('prepareContracts', importer.parse('id,buyer,description,date\nx,b,d,2025-02-30').records), /invalid date/);
assert.throws(() => run('prepareContracts', importer.parse('id,buyer,description,source\nx,b,d,javascript:alert(1)').records), /invalid source/);
console.log('Imported browse-only records cannot score; French opt-in, unknown currencies, exclusions and output validation passed.');
