#!/usr/bin/env python3
"""Interface translations, one table for Spanish and French.

  python tools/i18n-strings.py          # write i18n-es.js and i18n-fr.js
  python tools/i18n-strings.py --check  # fail if they are out of date (run by the tests)

EXACT: an English interface string (as rendered, whitespace-normalised) -> (es, fr).
PATTERNS: an English sentence with {slots} -> (es, fr). Slots capture data values, which stay
as published unless the value is itself an EXACT entry. Only interface text is translated;
source evidence keeps its original language (HANDOFF binding constraint).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from i18n_table import EXACT, PATTERNS, TITLES  # noqa: E402


def render(lang, index):
    exact = {en: tr[index] for en, *tr in EXACT}
    patterns = [[en, tr[index]] for en, *tr in PATTERNS]
    body = json.dumps({"title": TITLES[lang], "exact": exact, "patterns": patterns}, ensure_ascii=False, indent=1)
    return ("// Generated by tools/i18n-strings.py from tools/i18n_table.py: edit the table, not this file.\n"
            f"window.I18N_DICTS = window.I18N_DICTS || {{}};\nwindow.I18N_DICTS.{lang} = {body};\n")


def main():
    check = "--check" in sys.argv
    english = [en for en, *_ in EXACT]
    duplicates = sorted({en for en in english if english.count(en) > 1})
    if duplicates:
        raise SystemExit(f"duplicate English keys: {duplicates[:5]}")
    stale = []
    for lang, index in (("es", 0), ("fr", 1)):
        path = ROOT / f"i18n-{lang}.js"
        text = render(lang, index)
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            path.write_text(text, encoding="utf-8")
    if stale:
        raise SystemExit(f"out of date, run python tools/i18n-strings.py: {', '.join(stale)}")
    print(f"{len(EXACT)} exact strings and {len(PATTERNS)} patterns, Spanish and French")


if __name__ == "__main__":
    main()
